### ISSUE TITLE
[Mstore-pro] - ListAllscreen page show the Variable from AppConfig.json instead of the Value of variable

### ISSUE THREAD

**Issue by Gmlogy** [inspireui/support#1059]
---------
Mstore:
65ae6467-f067-450f-aa9d-6528a5ba0736

1. My issue
Hi, when i click " Show All" button it's redirect to a page that showing all products. the issue is in the top of screen i see the variable instead of the value.
for example i have a category named منتجات at Languages.js ( ProductFeatures: "منتجات", ) in Home screen i see the name that i set in Languages file but when i click to go to all category products i see  ProductFeatures instead of منتجات , Please how can i solve this issue ?
thank you

2. Screenshots
![sreen1](https://user-images.githubusercontent.com/52473562/64884642-2654c080-d65a-11e9-8d83-a86eb5841a6a.png)
![sreen2](https://user-images.githubusercontent.com/52473562/64884643-2654c080-d65a-11e9-8d64-d99e932f4561.png)

**Comment by minhcasi** [comment]
Hi, this could be a bug from the navigation, we will have a check and let you know - thank you!

@concuacon

**Comment by Gmlogy** [comment]
Hello ?

**Comment by concuacon** [comment]
@Gmlogy can you compress your folder common and send to me via tuan@inspireui.com? i'll check it.

**Comment by Gmlogy** [comment]
@concuacon i did it, thanks

**Comment by concuacon** [comment]
@Gmlogy i fixed it and sent to your mail

**Comment by Gmlogy** [comment]
@concuacon Thank you for your time, but the issue still there nothing was changed!!
