### ISSUE TITLE
FluxStore 1.6 - Product variations issue

### ISSUE THREAD

**Issue by csoftech** [inspireui/support#1650]
Hello,

I am running test on local and found that app shows all products with available variations and used varitions. 

It should display exactly it is shown on the site.

Screenshots will help.

![image](https://user-images.githubusercontent.com/35363714/71237819-92fdec00-2328-11ea-9b34-1616864e1dc0.png)
![image](https://user-images.githubusercontent.com/35363714/71237878-ae68f700-2328-11ea-9454-ac3e0d4341a9.png)
![image](https://user-images.githubusercontent.com/35363714/71237905-c2acf400-2328-11ea-98ff-3ff4f3b0e810.png)

As you can see on the mobile it shows all varitiation information as variations.

**Comment by minhcasi** [comment]
@csoftech - this is a known issue that was fixed by the team, we will send the patching on Monday - thank you!

**Comment by csoftech** [comment]
Thanks, waiting for the patch.

how do i update display of product page?

I want to have:

Sticky add to cart *No rating to be displayed (turned off from config still shows) *Display colours of left of the image as shown in the demo

*How do I update shop/category filters? It just shows category list, price & display style for category page. I need to display same amount of filters able on the site.

**Comment by csoftech** [comment]
Any updates?

**Comment by csoftech** [comment]
it is open , please respond. Many days passed with no resolution.

**Comment by minhcasi** [comment]
@vumanhsn97 - please help for suggestion

**Comment by csoftech** [comment]
what? do you bother to read?

**Comment by vumanhsn97** [comment]
@csoftech Sr. This bug is fixed but I dont find this issue on github. You can compare code in
- lib/models/product.dart https://tppr.me/pbvz4. 
- lib/services/woo_commerce.dart https://tppr.me/6X6oT
- replace file in lib/screens/detail/product_variant.dart to 
[product_variant.dart.zip](https://github.com/inspireui/support/files/4000044/product_variant.dart.zip)

**Comment by csoftech** [comment]
Thanks.

Can please check my query for filters ?

**Comment by csoftech** [comment]
** how do i update display of product page?
I want to have:
Sticky add to cart *No rating to be displayed (turned off from config still shows) *Display colours of left of the image as shown in the demo

** How do I update shop/category filters? It just shows category list, price & display style for category page. I need to display same amount of filters able on the site.

**Comment by minhcasi** [comment]
@csoftech - pls try to customize the UI base on your requirements by using the Inspector tool from Android Studio - https://docs.inspireui.com/fluxstore/useful-tip/#how-to-change-the-ui-quickly

**Comment by csoftech** [comment]
Thanks for your reply.

I am still clueless for additional filters ie. Color selection. Select Age
etc.

**Comment by minhcasi** [comment]
@csoftech - sorry as this is extra customization that we could not help, please try your best, thank you!

**Comment by csoftech** [comment]
are you kidding? if you don't provide support for such basic things what is the use of your support & app? Some demands are clearly from the demo? do you even BOTHER to READ ? or just reply?

1) Sticky add to cart 
2)No rating to be displayed (turned off from config still shows) 
3)Display colours of left of the image as shown in the demo
4) How do I update shop/category filters? It just shows category list, price & display style for category page. I need more filters like Choose from the colors & age(depending on the category selected).

**Comment by minhcasi** [comment]
@csoftech - the available features are the same as our demo on stores, you can process the refund if the app does not meet your requirements - thank you!

**Comment by csoftech** [comment]
I won't ask for refund if the product is having a bit of hope.

I dont see color options befor the picture of the product. (Screen shot
attached)

Also i dont see added to cart(cart button) button on product page
(screenshot attached.)
