### ISSUE TITLE
Flux new

### ISSUE THREAD

**Issue by Alqumairi** [inspireui/support#1844]
Hi

I have bought your plugin, after installing the plugins and link the app to the website, I have got some errors 

1- issues 
- The post are not loading at all in the home page is shows an error of (Invalid arguments).
- when i click on the posts categories it shows an error of (no such method error:  the getter "image feature was called on null")
- the registration page is working but when you register with facebook or other types of registration is not working at all. 

2- Screenshot
![Annotation 2020-01-16 144256](https://user-images.githubusercontent.com/37410069/72500180-e5222680-386e-11ea-90ce-b235e3eff389.png)
![Annotation 2020-01-16 144437](https://user-images.githubusercontent.com/37410069/72500181-e5222680-386e-11ea-85ba-26a8c337168d.png)
![Annotation 2020-01-16 144234](https://user-images.githubusercontent.com/37410069/72500182-e5babd00-386e-11ea-9740-5898a1b6c34e.png)

3- proof of purchasing 
![Annotation 2020-01-16 144922](https://user-images.githubusercontent.com/37410069/72500452-77c2c580-386f-11ea-8a6a-e830c7b99967.png)

4- Config files

`import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:fstore/common/constants.dart';

/// Server config
const serverConfig = {
  "url": "https://aswaqpress.com",
  "forgetPassword": "https://aswaqpress.com"
};

const CategoriesListLayout = kCategoriesLayout.card;

const CategoryStaticImages = {
  30: 'https://images.unsplash.com/photo-1448131063153-f1e240f98a72?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
  41: 'https://images.unsplash.com/photo-1496318447583-f524534e9ce1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
  45: 'https://images.unsplash.com/photo-1558920558-fb0345e52561?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
  46: 'https://images.unsplash.com/photo-1575301579296-39d50573daf5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
  40: 'https://images.unsplash.com/photo-1467453678174-768ec283a940?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
  37: 'https://images.unsplash.com/photo-1505678261036-a3fcc5e884ee?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
  31: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
  36: 'https://images.unsplash.com/photo-1555196301-9acc011dfde4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
  32: 'https://images.unsplash.com/photo-1517614138969-67d1892d0edf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
  33: 'https://images.unsplash.com/photo-1532301791573-4e6ce86a085f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
  34: 'https://images.unsplash.com/photo-1494919997560-caff2f1cff75?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1033&q=80',
};

/// the welcome screen data
List onBoardingData = [
  {
    "title": "Welcome to Aswaq Press",
    "image": "assets/images/fogg-delivery-1.png",
    "desc": "Bridging you to the arab worlds. "
  },
  {
    "title": "Connecting Surrounding World",
    "image": "assets/images/fogg-uploading-1.png",
    "desc":
        "See all things happening around you just by a click in your phone. "
            "Fast, convenient and clean."
  },
  {
    "title": "Let's Get Started",
    "image": "fogg-order-completed.png",
    "desc": "Waiting no more, let's see what we get!"
  },
];

/// Below config is use for further WooCommerce integration,
/// you can skip the config if not using WooCommerce
const afterShip = {
  "api": "e2e9bae8-ee39-46a9-a084-781d0139274f",
  "tracking_url": "https://aswaqpress.com"
};

const Payments = {
  "paypal": "assets/icons/payment/paypal.png",
  "stripe": "assets/icons/payment/stripe.png",
  "razorpay": "assets/icons/payment/razorpay.png",
};

/// The product variant config
const ProductVariantLayout = {
  "color": "color",
  "size": "box",
  "height": "option",
};

const kAdvanceConfig = {
  "DefaultLanguage": "en",
  "IsRequiredLogin": false,
  "GuestCheckout": true,
  "EnableShipping": false,
  "GridCount": 3,
  "DetailedBlogLayout": kBlogLayout.oneQuarterImageType,
  "EnablePointReward": false,
  "HeartButtonType": kHeartButtonType.cornerType,
};

/// The Google API Key to support Pick up the Address automatically
/// We recommend to generate both ios and android to restrict by bundle app id
/// The download package is remove these keys, please use your own key
const kGoogleAPIKey = {
  "android": "your-google-api-key",
  "ios": "your-google-api-key"
};

/// use to config the product image height for the product detail
/// height=(percent * width-screen)
/// isHero: support hero animate
const kProductDetail = {
  "height": 0.5,
  "marginTop": 0,
  "isHero": true,
  "safeArea": false,
  "showVideo": true,
  "showThumbnailAtLeast": 3
};

/// config for the chat app
const smartChat = [
  {
    'app': 'whatsapp://send?phone=84327433006',
    'iconData': FontAwesomeIcons.whatsapp
  },
  {'app': 'tel:8499999999', 'iconData': FontAwesomeIcons.phone},
  {'app': 'sms://8499999999', 'iconData': FontAwesomeIcons.sms},
  {'app': 'firebase', 'iconData': FontAwesomeIcons.google},
  {'app': 'intercome', 'iconData': FontAwesomeIcons.intercom},
];
const String adminEmail = "admininspireui@gmail.com";

const kIntercomAPIKey = {
  'android': 'android_sdk-2c16c0e017a1e7b8d3b73b5a13a56b54cbf535c0',
  'ios': 'ios_sdk-33135e6653b055cec773b7903baff10efee94bc0',
  'appID': 'xro9xnfd'
};

const kAdConfig = {
  "type": "",
  // ----------------- Facebook Ads  -------------- //

  "hasdedIdTestingDevice": "3f06ede0-3b68-4cdb-a639-1b1007cedd31",
  "bannerPlacementId": "430258564493822_489007588618919",
  "interstitialPlacementId": "430258564493822_489092398610438",
  "nativePlacementId": "430258564493822_489092738610404",
  "nativeBannerPlacementId": "430258564493822_489092925277052",

  // ------------------ Google Admob  -------------- //

  "androidAppId": "ca-app-pub-2101182411274198~7554000316",
  "androidUnitBanner": "ca-app-pub-2101182411274198/2054261627",
  "androidUnitInterstitial": "ca-app-pub-2101182411274198/7197727340",
  "androidUnitReward": "ca-app-pub-2101182411274198/5498660536",
  "iosAppId": "ca-app-pub-2101182411274198~6923444927",
  "iosUnitBanner": "ca-app-pub-2101182411274198/5418791562",
  "iosUnitInterstitial": "ca-app-pub-2101182411274198/9218413691",
  "iosUnitReward": "ca-app-pub-2101182411274198/9026842008",
  "waitingTimeToDisplayInterstitial": 10,
  "waitingTimeToDisplayReward": 10,
};
`
`{
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true
    },
    {
      "layout" : "header_text",
      "padding": 20.0,
      "fontSize": 30.0,
      "isSafeArea": false,
      "title" : "أخبار"

    },

    {
      "layout" : "largeCardHorizontalListItems",
      "imageBorder": 20.0,
      "category": 222
    },

    {
      "layout" : "sliderList",
      "type" :"",
      "name": {
        "en": "Recent Recipe",
        "ab": "Recent Recipe",
        "vi": "Recent Recipe"
      },
      "category": 221
    },

    {
      "layout" : "sliderList",
      "type" :"imageOnTheRight",
      "name": {
        "en": "Recent Recipe",
        "ab": "Recent Recipe",
        "vi": "Recent Recipe"
      },
      "category": 223
    },

    {
      "layout" : "sliderItem",

      "name": {
        "en": "Recent Recipe",
        "ab": "Recent Recipe",
        "vi": "Recent Recipe"
      },
      "category": 226
    },
    {
      "name": {
        "en": "Community Sharing",
        "ab": "Community Sharing",
        "vi": "Community Sharing"
      },
      "image": "",
      "layout": "staggered",
      "category": 256

    }
  ],

  "Setting": {
    "MainColor": "#ff0000",
    "ProductListLayout": "list"
  }
}
`

Flutter sdk version is 1.12.13

Please guide me how to fix the issues 

Thanks in advance

**Comment by minhcasi** [comment]
Fixed on latest 1.2.1 - pls download from http://codecayon.net/downloads - thank you!

**Comment by Alqumairi** [comment]
Hi

Some of the categories still show the same error. only in some of the categories. Please advice how to solve it


Thanks


![Annotation 2020-01-17 232516](https://user-images.githubusercontent.com/37410069/72623785-b300e980-3980-11ea-8ec8-5ec3885fb679.png)
