### ISSUE TITLE
Fluxstore Blog

### ISSUE THREAD

**Issue by amolsaini** [inspireui/support#2338]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Blog Error

2. Screenshots issues (required): 
![Untitled](https://user-images.githubusercontent.com/61465898/76571740-3d2b8100-64de-11ea-9a5c-7a8fe81d344b.jpg)

3. Proof of my purchased (required):
![licance](https://user-images.githubusercontent.com/61465898/76581845-bd5fdf80-64fa-11ea-965e-0ac19aa76c7c.jpg)

3. Config files (required) 

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building HalfImageType(dirty, dependencies: [MediaQuery], state: _HalfImageTypeState#3a941):
The method '*' was called on null.
Receiver: null
Tried calling: *(1.2)

The relevant error-causing widget was: 
  HalfImageType file:///C:/scr/source/lib/widgets/blog/blog_view.dart:28:16
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Tools.image (package:fstore/common/tools.dart:89:35)
#2      _HalfImageTypeState.build (package:fstore/widgets/blog/detailed_blog_half_image.dart:27:30)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)

**Comment by minhcasi** [comment]
@amolsaini - could you help to share the whole screenshot from http://codecayon.net/downloads that include your username :) - thank you!

**Comment by amolsaini** [comment]
Hi 
I have update Screenshot

**Comment by amolsaini** [comment]
HI

Any update ?

**Comment by amolsaini** [comment]
hi

I have been waiting for so long and there is no update about my issue.

**Comment by minhcasi** [comment]
confirmed the issue is fixed on the latest 1.6.5 - thank you!

**Comment by amolsaini** [comment]
hii
I am still getting error in new release ?

When will it get fixed

**Comment by minhcasi** [comment]
@amolsaini - could you share your common and config folder, we will help to check the integration issue on your site - thanks

**Comment by amolsaini** [comment]
please let me know your email

**Comment by dttrung26** [comment]
Hi @amolsaini ,
please kindly send your common folder via trung@inspireui.com. 
Have a nice day!

**Comment by amolsaini** [comment]
Hi dttrung26  
I have send both common and config folder a requested
Thanks

**Comment by amolsaini** [comment]
Hi any Update ??

**Comment by dttrung26** [comment]
Hi @amolsaini ,
please download the attached below file and replace it into /lib/widgets/blog/ and kindly tell me if it works.
[Github-support#2338.zip](https://github.com/inspireui/support/files/4378732/Github-support.2338.zip)

Nice day!

**Comment by dttrung26** [comment]
Hi @amolsaini ,
please download the attached below file and replace it into /lib/widgets/blog/ and kindly confirm if it works
[github_support#2338.zip](https://github.com/inspireui/support/files/4378745/github_support.2338.zip)

Nice day!

**Comment by amolsaini** [comment]
Hi 
I can confirm the issue is fixed Thank you dttrung26.

Regards
