### ISSUE TITLE
[Fluxstore - Woo] - [1.6.5] All Problems and solutions For 1.6.5

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2374]
@minhcasi 
Hello,
 
### (SOLVED)

I was shocked when a customer ordered after I sent the update to the play store today.

The app has a huge problem. It's a little difficult to explain.
Because I had a hard time understanding at first.

I will explain the problem first, then show it as a screen video.

This problem needs to be fixed urgently, otherwise "1.6.5" version is not available.

Problem;
customer adds "A (1x = $ 5)", "B (1x = $ 5)", "C (1x = $ 5)" to the basket. The customer adds a total of "$ 15" to the basket. then he goes to the payment screen and orders.

So far everything is normal.
But as it can be seen in the order history, there is also a problem with the panel on the website.

The problem is as follows;
product prices change in the order history, the total amount becomes the price of each product;
"A (1x = $ 15)", "B (1x = $ 15)", "C (1x = $ 15)". and the new total amount is $ 45. The total amount it should be is "$ 15".

Screen video =

![sorunbyk](https://user-images.githubusercontent.com/60021696/76846405-7e5ec080-6851-11ea-840b-8e37de018074.gif)

**Comment by minhcasi** [comment]
@philipvu30 - please help to investigate this issue - thank you!

**Comment by sketchuprzr** [comment]
Hello, this issue is very important to us and we would like to send updates soon. our customers are waiting for news from us. When can this problem be resolved?

**Comment by minhcasi** [comment]
related #2376 for new patching 1.6.5

@philipvu30 - please help this issue for high priority - thank you!

**Comment by sketchuprzr** [comment]
Hi @minhcasi
Is there any improvement ? I'm in a hurry, I'm aware of this. But this is important.. We need to release the update for our customers and campaigns. 


Secondly , Will there be a solution for the onesginal problem 

Thank you.

**Comment by philipvu30** [comment]
Hi @sketchuprzr ,
This issue is more complicated than we thought so we need a bit more time to fix it. We apologize for the delay or any inconvenience we may have caused. Thank you

**Comment by minhcasi** [comment]
@sketchuprzr - the latest version is available on gitlab, please have a check and let us know - thank you!

Please note that we will remove the onesignal from this release due to the unstable of the library that cause user's config issues - thank you!

**Comment by sketchuprzr** [comment]
Hello, @minhcasi 

thank you for the update.
Order problem is solved.

1) Has Onesignal been completely removed from the app? Won't it happen anymore?

2) The minimum amount for free shipping is still not working.

**Comment by sketchuprzr** [comment]
Hello, @minhcasi 

### 3)

### a solution related to product listing;

The application shows 10 products in each list.
However, the URL address he calls for listing contains "page = 1 & per_page = 20".
When the page continues, it continues as "page = 2 & per_page = 20".

10 items that do not appear on the first page are lost here.
To fix this, it is necessary to fix the URL addresses.

**"The number of products per page should be 10"**

![image](https://user-images.githubusercontent.com/60021696/77190789-f1369880-6aea-11ea-9127-49689a5ad493.png)

![image](https://user-images.githubusercontent.com/60021696/77190799-f562b600-6aea-11ea-9888-be8d8cbca0eb.png)

![image](https://user-images.githubusercontent.com/60021696/77190809-f85da680-6aea-11ea-906e-b157b6564022.png)

![image](https://user-images.githubusercontent.com/60021696/77190817-fbf12d80-6aea-11ea-907f-7377419dde2e.png)

![image](https://user-images.githubusercontent.com/60021696/77190824-feec1e00-6aea-11ea-8f4f-8fdcb3d6081d.png)

![image](https://user-images.githubusercontent.com/60021696/77190839-057a9580-6aeb-11ea-9a35-72b1972d9d96.png)

---------------------------------------------------
### 4)

A feature that comes in at 1.6.5,

Located in the filter option

"Attributes" and "Tags"
attracts up to 10 items to the app.

It doesn't show more than 10 items.

![image](https://user-images.githubusercontent.com/60021696/77191174-98b3cb00-6aeb-11ea-8ea6-664eb08a6de7.png)

**Comment by minhcasi** [comment]
@sketchuprzr - thank you for quickly feedbacks.

1 - We disable the function from onesignal and remove from pubspec temporary now, we may support this library again still it is stable, so far there is some suddence issues that cause the build brokend - related to #2395 (the reason is they change the grade version), you can still use this function if have some background on this library

2 - could you share your test case ?

3.4 - thank you for your sharing the solutions and confirm

5 - to need to rename the startAnimate name to meet with the name on tool - https://tppr.me/kLbnt

**Comment by sketchuprzr** [comment]
Hi @minhcasi 

### For 1)
I am sorry that onesignal has been removed. A much nicer system than onesignal fcm.

### For 2)
For problem (2), I sent you the application's source files by email.
Mail address I sent: minhcasi@gmail.com

### For 5)
Thanks for solution "5" . The "5" problem solved. you can write this information in doc.inspireui.

### One question 
Can it be an automatic player for "banner image"? It would be nice to have an automatic rotation every 2 or 3 seconds. or, it would be nice if there were arrow buttons on the right and left. because it is not clear that this "banner image" is a continuation.

![image](https://user-images.githubusercontent.com/60021696/77235496-303a1c00-6bc7-11ea-9fb9-3aaecc2f2d4a.png)

![image](https://user-images.githubusercontent.com/60021696/77235465-ecdfad80-6bc6-11ea-822b-5b22800fc33c.png)

**Comment by philipvu30** [comment]
Hi @sketchuprzr ,

About the "Auto Banner Image", there are 3 attributes you need to add to the config:
- "autoPlay" : true
- "intervalTime" : 3
- "design" : "default"
You can change the "default" to "swiper", "stack" or "tinder"

Fixed issues: 2 and 6
Issue number 3: I quite don't get your problem. Would you mind give me a more detailed explanation with images included?
Issue number 7: We'll need to discuss this with our team on the implementation decision.

**Comment by sketchuprzr** [comment]
Hello, @philipvu30 
 
Heading number 3 is not a problem, but a solution to a problem.

(The application displays 10 products on 1 page. But he buys 20 products from the site. I fixed this number to 10. In this way, the application shows all products.
otherwise, the application does not show all products. this is breaking the algorithm.)


Thank you for solutions number 2 and 6.

when are these solutions shared?

Thank you.

**Comment by philipvu30** [comment]
Hi @sketchuprzr ,

We will update the new version on the weekend.
For the issue number 3, I still not get what you are trying to explain. I have tried to reproduce the issue but everything seems fine.

**Comment by sketchuprzr** [comment]
I will shoot and send you a video about topic "3" soon so that you can understand it better. @philipvu30
