### ISSUE TITLE
[Fluxstore Pro] : catgory page doesn't load more than 10 products (bug report)

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#2974]
* 
I just notice not all the products loading when I enter any category in the app it only shows 10 products no matter how many products in the category:  

*
See this video explain - https://imgur.com/a/5nVn4dt

 

*
I verified my purchase code and upload the Config Files through - http://private.inspireui.com

**Comment by abqrinou** [comment]
you can try to change The time zone and Date Format from wordpress Settings . and add Category base (Category)from Permalink Settings

**Comment by minhcasi** [comment]
@Alnaggar94 - we have investigated and fixed this issue on next release, we will load this patching on Gitlab or release a new version on next couple of day 

- thank you

**Comment by Alnaggar94** [comment]
@minhcasi @abqrinou - Thank you so much I really appreciate your work I will be waiting for the fix on Gitlab,
There is also a missing translation on Login by SMS screen it only has one language English only:

![h5](https://user-images.githubusercontent.com/49800146/80852504-c97e3880-8c31-11ea-81e4-aed74e1aa958.JPG)

*
How do I sort the categories in the category screen, for example, Electronic first cloths second ...etc. it sort randomly and that's not good could you please help with it.

![h6](https://user-images.githubusercontent.com/49800146/80852588-76f14c00-8c32-11ea-8ba2-47a9ac15ecbb.JPG)

**Comment by minhcasi** [comment]
we have fixed this bug on the latest 1.7.2 - pls help to download the package - thank you!

**Comment by Alnaggar94** [comment]
@minhcasi - but the other two issues above not solved, please see my comment https://github.com/inspireui/support/issues/2974#issuecomment-622653396
