### ISSUE TITLE
Launch IOS Simulator

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#301]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**
When i would like run the IOS Simulator  , i have this error 
**Screenshots**
![image](https://user-images.githubusercontent.com/47614045/52748617-469a9f00-2fe7-11e9-9ef3-c5d6664e6fa9.png)

**Additional context**
INFO
23:22
Starting Metro Bundler on port 19001.
INFO
23:22
Tunnel ready.
INFO
23:22
Opening iOS simulator
INFO
23:22
Downloading latest version of Expo
INFO
23:22
Installing Expo on iOS simulator
ERROR
23:22
Error running `xcrun simctl install booted /Users/heyckelneji/.expo/ios-simulator-app-cache/Exponent-2.10.0.app`: An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
Unable to lookup service com.apple.CoreSimulator.host_support: 0x3
Underlying error (domain=NSPOSIXErrorDomain, code=3):
	The operation couldn’t be completed. No such process
	No such process
ERROR
23:22
Error installing or running app. Error: Process exited with non-zero code: 164

**Comment by luyx2412** [comment]
Hi @hakihosting Please provide your purchase code.

Thanks

**Comment by hakihosting** [comment]
Item Purchase Code:

ac9d522a-a783-4f9c-a882-7dc694488d5d

 

De : luyx2412 <notifications@github.com>
Répondre à : inspireui/support <reply@reply.github.com>
Date : jeudi 14 février 2019 à 03:32
À : inspireui/support <support@noreply.github.com>
Cc : hakihosting <contact@haki-hosting.be>, Mention <mention@noreply.github.com>
Objet : Re: [inspireui/support] Launch IOS Simulator (#301)

 

Hi @hakihosting Please provide your purchase code.

Thanks

**Comment by hakihosting** [comment]
some news ?

**Comment by luyx2412** [comment]
HI @hakihosting Please follow the comment to fix your issue https://stackoverflow.com/a/44780772/6622971. 

Thanks

**Comment by hakihosting** [comment]
i deleted the file , and reload and restard the ios simulator same problem.

Error installing or running app. ZlibError: zlib: invalid stored block lengths

**Comment by hakihosting** [comment]
some news please is urgent

**Comment by luyx2412** [comment]
HI @hakihosting Are you try https://stackoverflow.com/a/51671111/6622971. 
Or you can click two times `Run on IOS simulator`. The first time it will show error, the second time it will work normal.

Thanks

**Comment by hakihosting** [comment]
it's work i must do that : However, if it still fails, Erasing all content and settings on the simulator does the trick too.

**Comment by hakihosting** [comment]
can i use cebuilder for the pro version ?

**Comment by minhcasi** [comment]
Hi, yes - it also supports the pro version to work with CeBuilder

Btw, do you mind if posting all your issues to one ticket? That will help to team focus on your is your detail issues and not mess up the Ticket support channel. We will close other ticket and combine your all issues to this one ticket, please keep update from here - thank you!

#307 - please edit from the common/languages.js file
#308 - Could you send us your AppConfig.js and config.js for checking ?
#309 - There is the config option from AppConfig.json to control these homepage layout, looks like you have miss config the Header Banner at the top
#310 - the shipping method could be control from the config.js file, you can add the option from this file. The shipping address is pick up from the Billing Address of the user.

**Comment by hakihosting** [comment]
Ok sorry mate. I know now for the second time 

#307 :  i have like this 

export default {
  Exit: "Exit",
  ExitConfirm: "Are you sure you want to exit this app",
  YES: "YES",
  OK: "OK",
  ViewMyOrders: "View My Oders",
  CANCEL: "CANCEL",
  Confirm: "Confirm",

How can i do do let the user choice which language do they want  when they launch the app 

#308 : 
Appconfig.js 

{
  "WooCommerce": {
    "url": "http://chakcwear.com",
    "consumerKey": "ck_69186ecbbcaacc2c872481f6f0050b844d615f65",
    "consumerSecret": "cs_0e302c88a90b97dce8c327be68f00b103025d4e9"
  },
  "HorizonLayout": [
    {
      "name": "Feature Products",
      "layout": 6,
      "categoryOrTag": 50,
      "category": 50
    },
    {
      "name": "Bags Collections",
      "image": "",
      "layout": 6,
      "categoryOrTag": 51,
      "category": 51
    }
  ],
  "MainColor": "#333"
}

COnfig.js

/** @format */

import Images from "./Images";
import Constants from "./Constants";
import Icons from "./Icons";

export default {
  /**
   * Step 1: change to your website URL and the wooCommerce API consumeKey
   * Moved to AppConfig.json
   */

  /**
     Step 2: Setting Product Images
     - ProductSize: Explode the guide from: update the product display size: https://mstore.gitbooks.io/mstore-manual/content/chapter5.html
     The default config for ProductSize is disable due to some problem config for most of users.
     If you have success config it from the Wordpress site, please enable to speed up the app performance
     - HorizonLayout: Change the HomePage horizontal layout - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html
       Update Oct 06 2018: add new type of categories
       NOTE: name is define value --> change field in Language.js
       Moved to AppConfig.json
     */
  ProductSize: {
    enable: true
  },

  HomeCategories:[
      {category: 18, image : require("@images/categories_icon/ic_shorts.png"), colors: ["#4facfe", "#00f2fe"] },
      {category: 21, image : require("@images/categories_icon/ic_tshirt.png"), colors: ["#43e97b", "#38f9d7"] },
      {category: 208, image : require("@images/categories_icon/ic_panties.png"), colors: ["#fa709a", "#fee140"] },
      {category: 26, image : require("@images/categories_icon/ic_dress.png"), colors: ["#7F00FF", "#E100FF"] },
      {category: 24, image : require("@images/categories_icon/ic_glasses.png"), colors: ["#30cfd0", "#330867"] },
      {category: 212, image : require("@images/categories_icon/ic_shoes.png"), colors: ["#2af598", "#009efd"] },
      {category: 213, image : require("@images/categories_icon/ic_tie.png"), colors: ["#6a11cb", "#2575fc"] },
      {category: 211, image : require("@images/categories_icon/ic_socks.png"), colors: ["#c471f5", "#fa71cd"] },
      {category: 210, image : require("@images/categories_icon/ic_woman_shoes.png"), colors: ["#f43b47", "#453a94"] },
  ],
  /**
     step 3: Config image for the Payment Gateway
     Notes:
     - Only the image list here will be shown on the app but it should match with the key id from the WooCommerce Website config
     - It's flexible way to control list of your payment as well
     Ex. if you would like to show only cod then just put one cod image in the list
     * */
  Payments: {
    bacs: require("@images/payment_logo/PayPal.png"),
    cod: require("@images/payment_logo/cash_on_delivery.png"),
    paypal: require("@images/payment_logo/PayPal.png"),
    stripe: require("@images/payment_logo/stripe.png"),
    bacss: require("@images/payment_logo/bancontact.png"),
  },

  /**
     Step 4: Advance config:
     - showShipping: option to show the list of shipping method
     - showStatusBar: option to show the status bar, it always show iPhoneX
     - LogoImage: The header logo
     - LogoWithText: The Logo use for sign up form
     - LogoLoading: The loading icon logo
     - appFacebookId: The app facebook ID, use for Facebook login
     - CustomPages: Update the custom page which can be shown from the left side bar (Components/Drawer/index.js)
     - WebPages: This could be the id of your blog post or the full URL which point to any Webpage (responsive mobile is required on the web page)
     - CategoryListView: default layout for category (true/false)
     - intro: The on boarding intro slider for your app
     - menu: config for left menu side items (isMultiChild: This is new feature from 3.4.5 that show the sub products categories)
     * */
  shipping: {
    visible: true,
    zoneId: 1, // depend on your woocommerce
    time: {
      free_shipping: "4 - 7 Days",
      flat_rate: "1 - 4 Days",
      local_pickup: "1 - 4 Days",
    },
  },
  showStatusBar: true,
  LogoImage: require("@images/logo-main.png"),
  LogoWithText: require("@images/logo_with_text.png"),
  LogoLoading: require("@images/logo.png"),

  showAdmobAds: false,
  AdMob: {
    deviceID: "pub-2101182411274198",
    unitID: "ca-app-pub-2101182411274198/4100506392",
    unitInterstitial: "ca-app-pub-2101182411274198/8930161243",
    isShowInterstital: true,
  },
  appFacebookId: "189268595244786",
  CustomPages: { contact_id: 10941 },
  WebPages: { marketing: "http://chakcwear.com/" },


  intro: [
    {
      key: "page1",
      title: "Nouveaux Design de l'application",
      text:
        "Un tout nouveaux design de l'application , plus fluide et plus facile",
      icon: "ios-basket-outline",
      colors: ["#0FF0B3", "#036ED9"],
    },
    {
      key: "page2",
      title: "Paiement amélioré",
      text:
        "Carte de crédit , paypal , carte de banque",
      icon: "ios-card-outline",
      colors: ["#13f1fc", "#0470dc"],
    },
    {
      key: "page3",
      title: "Connexion sécurisée",
      text: "Un compte encore plus sécurisée",
      icon: "ios-finger-print-outline",
      colors: ["#b1ea4d", "#459522"],
    },
  ],

  /**
   * Config For Left Menu Side Drawer
   * @param goToScreen 3 Params (routeName, params, isReset = false)
   * BUG: Language can not change when set default value in Config.js ==> pass string to change Languages
   */
  menu: {
    // has child categories
    isMultiChild: true,
    // Unlogged
    listMenuUnlogged: [
      {
        text: "Login",
        routeName: "LoginScreen",
        params: {
          isLogout: false,
        },
        icon: Icons.MaterialCommunityIcons.SignIn,
      },
    ],
    // user logged in
    listMenuLogged: [
      {
        text: "Logout",
        routeName: "LoginScreen",
        params: {
          isLogout: true,
        },
        icon: Icons.MaterialCommunityIcons.SignOut,
      },
    ],
    // Default List
    listMenu: [
      {
        text: "Shop",
        routeName: "Home",
        icon: Icons.MaterialCommunityIcons.Home,
      },
      {
        text: "News",
        routeName: "NewsScreen",
        icon: Icons.MaterialCommunityIcons.News,
      },
      {
        text: "contactus",
        routeName: "CustomPage",
        params: {
          id: 10941,
          title: "contactus",
        },
        icon: Icons.MaterialCommunityIcons.Pin,
      },
      {
        text: "Instagram",
        routeName: "CustomPage",
        params: {
          url: "https://www.instagram.com/chakcwear/?hl=fr",
        },
        icon: Icons.MaterialCommunityIcons.Email,
      },

      {
        text: "Snapchat",
        routeName: "CustomPage",
        params: {
          url: "https://www.snapchat.com/add/chakcwear",
        },
        icon: Icons.MaterialCommunityIcons.Email,
      },
      // {
      //   text: "Setting",
      //   routeName: "SettingScreen",
      //   icon: Icons.MaterialCommunityIcons.Setting,
      // },
    ],
  },

  // define menu for profile tab
  ProfileSettings: [
    {
      label: "WishList",
      routeName: "WishListScreen",
    },
    {
      label: "MyOrder",
      routeName: "MyOrders",
    },
    {
      label: "Address",
      routeName: "Address",
    },
    {
      label: "Currency",
      isActionSheet: true,
    },
    // only support mstore pro
    //   {
    //     label: Languages.Languages,
    //     routeName: 'SettingScreen',
    //     value: language.lang,
    //   },
    {
      label: "PushNotification",
    },
    {
      label: "contactus",
      routeName: "CustomPage",
      params: {
        id: 10941,
        title: "contactus",
      },
    },
    {
      label: "Privacy",
      routeName: "CustomPage",
      params: {
        url: "https://inspireui.com/privacy",
      },
    },
    {
      label: "termCondition",
      routeName: "CustomPage",
      params: {
        url: "https://inspireui.com/term-of-service",
      },
    },
    {
      label: "About",
      routeName: "CustomPage",
      params: {
        url: "http://inspireui.com",
      },
    },
  ],

  // Layout select
  layouts: [
    {
      layout: Constants.Layout.card,
      image: Images.icons.iconCard,
      text: "cardView",
    },
    {
      layout: Constants.Layout.simple,
      image: Images.icons.iconRight,
      text: "simpleView",
    },
    {
      layout: Constants.Layout.twoColumn,
      image: Images.icons.iconColumn,
      text: "twoColumnView",
    },
    {
      layout: Constants.Layout.threeColumn,
      image: Images.icons.iconThree,
      text: "threeColumnView",
    },
    {
      layout: Constants.Layout.horizon,
      image: Images.icons.iconHorizal,
      text: "horizontal",
    },
    {
      layout: Constants.Layout.advance,
      image: Images.icons.iconAdvance,
      text: "advanceView",
    },
  ],

  // Default theme loading, this could able to change from the user profile (reserve feature)
  Theme: {
    isDark: false
  },

  // new list category design
  CategoryListView: true,

  DefaultCurrency:{
    symbol: "€",
    name: "Euro",
    code: "EUR",
    name_plural: "EURO",
    decimal: ".",
    thousand: ",",
    precision: 2,
    format: "%v %s", // %s is the symbol and %v is the value
  },

  DefaultCountry: {
    code: "fr",
    RTL: false,
    language: "French",
    countryCode: "FR",
    hideCountryList: true // when this option is try we will hide the country list from the checkout page, default select by the above 'countryCode'
  },
  HideCartAndCheckout: false,

  /**
   * Config notification onesignal
   */
  OneSignal: {
    appId: "28ad48af-221d-454b-9e8e-fe6c76f7fdb1",
  },
  /**
   * Login required
   */
  Login: {
    RequiredLogin: false, // required before using the app
    AnonymousCheckout: false, // required before checkout or checkout anonymous
  },
  HideCartAndCheckout: false
};

#309 : where i didn't see 

#310 :  I would like to propose the same means of delivery and conditions as there are on the site.

Belgium
Fixed price: basic conditions if the order is not more than 70
Free: when an order is more than 70 euro order 


France 
Fixed price: basic conditions if the order is not more than 100
Free: when an order is more than 100 euro order

**Comment by hakihosting** [comment]
Some news

**Comment by luyx2412** [comment]
Hi @hakihosting Please send the file and format your comment to see easier. Currently i did not understand what you mean and your question.

Thanks

**Comment by hakihosting** [comment]
#307 : i have like this  : How can i do do let the user choice which language do they want when they launch the app
[Languages.js.zip](https://github.com/inspireui/support/files/2888253/Languages.js.zip)

#308 :
[AppConfig.json.zip](https://github.com/inspireui/support/files/2888259/AppConfig.json.zip)

#309 : where i didn't see

#310 : I would like to propose the same means of delivery and conditions as there are on the site.

Belgium
Fixed price: basic conditions if the order is not more than 70
Free: when an order is more than 70 euro order

France
Fixed price: basic conditions if the order is not more than 100
Free: when an order is more than 100 euro order

**Comment by hakihosting** [comment]
Some news please ?

**Comment by hakihosting** [comment]
???

**Comment by luyx2412** [comment]
Hi @hakihosting Sorry about reply late.

1. Currently i just see one language in your file. If you want to move Switch language in first running app. You will see the `LangagePicker.js` file in path `src/containers/Setting/LanguagePicker.js` in MStore Pro. 

2. I just fixed the issue in next version. You can quick fix to wait next version. In `src/common/Constants.js` file. Please change your `Language: "English"` to `Language: "en"` look like the photo. https://www.screencast.com/t/WTw2kkmUD

3. In your `Language.js` file. Make sure you have config look like `Config.js` file.

4. You can edit on your site. Because currently the delivery use based on your config site.

Thanks

**Comment by hakihosting** [comment]
1: how can i set ENglish and french it's possible to send me exemple 
2: same  problem => https://ibb.co/YfSy7WC
3. yes i have set your default text :   bagsCollections: "Bags Collections", 

4. yes but the conditions on my website is set
 Fixed price: basic conditions if the order is not more than 100
Free: when an order is more than 100 euro order
Or in the app there is no conditions ? how can i do the same ?

**Comment by luyx2412** [comment]
Hi @hakihosting 
- The Mstore expo version did not support multi language, please move to Mstore pro.
- We will update next expo version to fix the issue.
- I don't understand, you still show default from own source normal? Because `bagsCollections` is the field name.
- You can edit in `src/containers/Cart/Payment/index.js` with function `getShippingMethod`. Check your condition in this function.

Thanks

**Comment by hakihosting** [comment]
Ok i move to mstore pro 
when i would like to run ios setup  : i have this error 

Impossible to open "cebuilder.sh" because Sandbox is not allowed to open documents in Terminal.

**Comment by hakihosting** [comment]
* You can edit in `src/containers/Cart/Payment/index.js` with function `getShippingMethod`. Check your condition in this function.

How can i retrieve the amount of cart  , and apply condtion about that ?

**Comment by luyx2412** [comment]
Hi @hakihosting In redux store we saved cart item. You can get the amount of cart. Please read the document https://redux.js.org/ to get data from redux store.

Thanks

**Comment by hakihosting** [comment]
Hello , i'am sorry but is not closed , I have still problem to display categories can you help me ? or not
