### ISSUE TITLE
[fluxstore Pro] on boarding screen is shown everytime app is open

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3275]
Step 1 (require): detail issues and screenshots

After updating to new version 1.7.4 onboarding screen is shown again and again. Even onboarddingfirstonly time setting is set true in general .config

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@tjain90 - this bug is fixed, we will update new release today 👍

**Comment by tjain90** [comment]
@minhcasi Above bug is still there. Login screen is shown everytime app is open. I have updated to new version that was released yesterday.
