### ISSUE TITLE
Webview Payment Gateway Returns 404 Error & status bar color Error too...!

### ISSUE THREAD

**Issue by masthan8** [inspireui/support#3508]
**_Step 1 (require): describe detail issues & screenshots_**

+ Detail Issues: 

**Issue 1:The web view payment gateway is not working. Its returning a 404 page, tried switching between native type and also one page checkout. Its all the same, only 404 page returns. But its working fine in the website. NOTE: searched for similar issues in github support and found few fixes and tried all. But no use. 

Issue 2: The status bar color, sometimes its showing but most of the time its not showing and its overlapping with the app header color. Its persists in both the dark mode and normal mode. You can check screenshot 1 status bar. Its the same in many pages, the product details etc.** 

Issue 3: The privacy policy page is not working

Also need to know how to create few other pages and add to settings menu, like terms and conditions, contact us, etc. 

+ Product & version: 1.7.4 (Latest)

+ Flutter (or React Native) version: Latest

+ Testing Device/Simulator: Google Pixel 3A

+ Screenshot issues (drag the file to attach here): 
![Screenshot_1590930597](https://user-images.githubusercontent.com/43437325/83353563-26b5f880-a35c-11ea-9da4-6ad81f50a3f2.png)

![Screenshot_1590930638](https://user-images.githubusercontent.com/43437325/83353564-287fbc00-a35c-11ea-9e28-bff0becf06bd.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
****Already Verified.**** 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by masthan8** [comment]
Update, 

If I set False to both the payment page types then the Native payment type is working and its taking me to the payment gateway page in webview. But if I set either one to true then its showing 404 page. 

Also when it goes to payment gateway page for few seconds its showing the shipping address anc checkout page and not directly going to the payment gateway page.

**Comment by minhtruong315** [comment]
Hi @masthan8 can u send me admin account to login to your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3508

**Comment by masthan8** [comment]
Hi,

Sent details via email.. pls check

**Comment by minhtruong315** [comment]
Thanks @masthan8 I will check and let you know soon.

**Comment by minhtruong315** [comment]
Hi @masthan8 can u upload your source code to github then invite me: minhtruong315@gmail.com
I'll help you fix on your source code.
Thanks

**Comment by minhtruong315** [comment]
@masthan8 for issue 3, Fluxstore doesn't support config more pages. But you can update source code like this
<img width="1180" alt="Screen Shot 2020-06-05 at 5 34 46 PM" src="https://user-images.githubusercontent.com/10402500/83867087-0bc7f780-a753-11ea-8aab-2568e91b6a67.png">

For issue 2, we will investigate and update it
Thanks

**Comment by masthan8** [comment]
Hi, 
what about the issues 1? its important more than anything else...

**Comment by masthan8** [comment]
Hi, Invitation sent to access git source code..

**Comment by fab17an** [comment]
Good, I have the same problem as my colleague with the payment method, he throws me the 404 error, if I pay with cash on delivery, everything is normal, the issue is card payment

**Comment by minhtruong315** [comment]
Hi @masthan8 I fixed issue 1 on your source code. please pull the source code and check again.
Thanks

**Comment by minhtruong315** [comment]
@masthan8 how? let me know the result.
Thanks

**Comment by masthan8** [comment]
Hi,

Thanks for the information.. let me.check the source code and get back to
you. Kindly keep the ticket open. I ll close it once the issue is fixed.

**Comment by masthan8** [comment]
Hi @minhtruong315 ,

Checked and its working fine now, but will this fix be included in the future coming updates of the source code?

Also any updates on my issue 2? thats also important, i checked on your multi vendor app also and its the same there also. Status bar and the app bar has got issues with the color..

**Comment by minhtruong315** [comment]
Hi @masthan8 I will check issue 2 and update it on the next release. Thanks

**Comment by minhcasi** [comment]
Fixed on the latest `1.7.6`, let us know if you have any issues - thank you!

**Comment by masthan8** [comment]
Hi, 

Tested the new version and the design issues I have mentioned above is not fixed. Still the status bar color in the products page, my cart page, and in products page when we  scroll down the top bar gets white and he status bar is not showing any status icons. These are all very important as it affects the quality of the brand. 

Please check that.
