### ISSUE TITLE
I have an issue when i switch currency

### ISSUE THREAD

**Issue by kibbyboi** [inspireui/support#3814]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@kibbyboi - got your verified comment 

Could you help to share your `lib/common` and `lib/config` folder so that we could help for investigating - thank you!

**Comment by kibbyboi** [comment]
> @kibbyboi - got your verified comment
> 
> Could you help to share your `lib/common` and `lib/config` folder so that we could help for investigating - thank you!

Alright let me do so

**Comment by kibbyboi** [comment]
Send via email

**Comment by minhcasi** [comment]
@kibbyboi - pls help to send via this form  http://verify.inspireui.com or attache via this email - thank you!

**Comment by kibbyboi** [comment]
I just submitted everything.

**Comment by kibbyboi** [comment]
Hello any response to my issue

**Comment by kibbyboi** [comment]
Hello guys, it's been two days now no answer or response

**Comment by minhcasi** [comment]
@kibbyboi - could i check if you have install the WPML plugin and config as this guide - https://docs.inspireui.com/fluxstore/customization/#9-product-advance-options

Is it possible to share your website login so that we could help for checking - pls share to support@inspireui.com - thanks

**Comment by kibbyboi** [comment]
I will do so now

**Comment by kibbyboi** [comment]
Check attachment. Login details

**Comment by minhcasi** [comment]
Hi, we did not get it, could i know your email address? Thanks

**Comment by kibbyboi** [comment]
Can i get a solution please, our app really depends on this currency
exchange feature to work if we going to do business. It's been 7 days since
logged this issue

**Comment by minhcasi** [comment]
@kibbyboi - would you mind to resend the log in detail to support@inspireui.com - as the previous comment we could not get your detail - thank you for your time

**Comment by kibbyboi** [comment]
I added you on our website backend. I have attached a screenshot of your
login details on this picture , check it out on attachment

**Comment by minhcasi** [comment]
Hi @kibbyboi - i could not you get your detail info from the latest email 

<img width="848" alt="Screen Shot 2020-07-02 at 10 40 50" src="https://user-images.githubusercontent.com/1459805/86313916-800d9200-bc50-11ea-9380-4d1ad783f2ee.png">

**Comment by kibbyboi** [comment]
This is annoying 😠, I have put details on the attachment.a picture, how
many times I am going to say that.

**Comment by kibbyboi** [comment]
![Screenshot_2020-07-02-10-48-14-882_com whatsapp w4b](https://user-images.githubusercontent.com/4435840/86338133-3f167d00-bc52-11ea-852f-05f2795b674b.jpg)
Look our customers are tired waiting for this feature can you help please

**Comment by minhcasi** [comment]
@kibbyboi - what you mean on the attache screenshot? We did not chat with you about these messages? Regarding the `store app` demo, what is the link?

The solution to add new currency already explain via document: https://docs.inspireui.com/fluxstore/customization/#9-product-advance-options, you also need to add new currency into WPML setting

**Comment by kibbyboi** [comment]
I was showing how important i need this feature to work, our customers are
asking for it, ability to change currency and for it to show current
exchange rate on the App.

**Comment by kibbyboi** [comment]
We have Added new currency but the exchange rate is not working, we have
also added plugins needed

**Comment by kibbyboi** [comment]
Still response from you guys

**Comment by minhcasi** [comment]
@kibbyboi - feel free to customize the API to fetch the exchange rate from WPML and display from the currency switching screen.

There is also the bug from switching currency product variant  - we also fix the and will release on 1.6.7, you could download the latest code on our gitlab in next 1-2 days (this fixing also apply the exchange rate that could be fixed your case) - thank you!

**Comment by kibbyboi** [comment]
Thank you very much for your reply. I appreciate it. I will wait for it

**Comment by andyodoo** [comment]
@minhcasi I'm having the same problem in switching currencies 
I'm able to switch currencies and see the correct rate in  all products (shop)page  
but we i entered the product page its shows only base currency 

the products page
<img width="537" alt="Screen Shot 2020-07-08 at 12 20 37 PM" src="https://user-images.githubusercontent.com/50452375/86901544-7040f280-c115-11ea-9844-4b059141fc0e.png">

the product page 
<img width="537" alt="Screen Shot 2020-07-08 at 12 20 52 PM" src="https://user-images.githubusercontent.com/50452375/86901578-7b941e00-c115-11ea-9efb-0f0beb462ced.png">


please help us fix it

**Comment by minhcasi** [comment]
The latest release is available on gitlab, we will update new package on Monday - thank you!

**Comment by minhcasi** [comment]
Fixed on the latest `1.7.6`, let us know if you have any issues - thank you!

**Comment by kibbyboi** [comment]
I hello I need help, I am currently having issues with latest version of
your app it's crashing on start after I install it on my phone but on
Android studio it's working fine when I run it, help

**Comment by kibbyboi** [comment]
Hello Support Team. I am kindly asking for help I am still facing issues
with currency in the new build , after switching currencies the exchange
rate does not update prices based on the selected currency. I don't know
what can be done to make it please help I really need this work otherwise
my customers are doomed on using our app. Thank you
