### ISSUE TITLE
Home Tab Showing 2 times Load more and see all Options

### ISSUE THREAD

**Issue by omman** [inspireui/support#3825]
Hi @vumanhsn97 it has sam issues today i update and check it has same issues.https://drive.google.com/file/d/1rgZABKt9TQ12-G9PkEo6z-se7BcKhV5u/view?usp=sharing
https://play.google.com/store/apps/details?id=qa.qutoof.store app link
<blockquote><img src="https://lh5.googleusercontent.com/FMpqOhCJ9VKN1g3tEdjf2qimYH7jbBuNTxw12icR-EgqNOSArBsHN9dRRegPlAQ=w1200-h630-p" width="48" align="right"><div>Google Drive</div><div><strong><a href="https://drive.google.com/file/d/1rgZABKt9TQ12-G9PkEo6z-se7BcKhV5u/view?usp=sharing&usp=embed_facebook">1592556696-video.mp4</a></strong></div></blockquote>

_Originally posted by @omman in https://github.com/inspireui/support/issues/3536#issuecomment-646960186_

**Comment by ameenbadri7** [comment]
i guss on your config.json file you have duplicate the 

 ```
 "VerticalLayout": {
    "layout": "list",
    "name": "Recent Collections"
  },
```

can you share your config file here .

**Comment by omman** [comment]
@ameenbadri7 we not put this 2 times.

**Comment by omman** [comment]
@ameenbadri7 Please take this https://drive.google.com/file/d/1JvdzVHyyr3D4JKcrpcB1eilNAyVRfSD_/view?usp=sharing config files.

**Comment by ameenbadri7** [comment]
I have config with your configs and I have the same problem too.
I see the problem now. It shows after the user login and comes back to the home page it's doubled the list. 

I will contact the support team now to investigate. and they will fix it.

**Comment by kvt0012** [comment]
If you upgrade to newer version, please copy the old code @vumanhsn97  given to you, because when you update it, it will be replaced. Thank you

**Comment by omman** [comment]
Hi @kvt0012 there is no new code, there is no old code, this problem is from old code and new code both.

**Comment by kvt0012** [comment]
I see your previous ticket and vumanhsn97 is fixed it for you and it works, so you just simple copy code that vumanhsn97 sent to you on the new version and check whether it fixed or not. 
![image](https://user-images.githubusercontent.com/49152325/86108826-dca46c00-baed-11ea-9edb-223fd17dbf0f.png)

**Comment by omman** [comment]
@kvt0012 It's not fixed that i am saying every time, why not understand..

**Comment by kvt0012** [comment]
I'm sorry because I see that you comment it is fixed, so I think it works for you, sir

**Comment by kvt0012** [comment]
https://github.com/inspireui/support/files/4804032/index.dart.zip 
Please try this, sir

**Comment by omman** [comment]
@kvt0012 I try not worked..

**Comment by minhcasi** [comment]
Fixed on the latest 1.7.6, let us know if you have any issues - thank you!

**Comment by omman** [comment]
Hi, I want to ask you do i need to update again from beginning, Because every time we can see old files and code not worked, so if we customize the process do i need to change again with new version?

**Comment by minhcasi** [comment]
we suggest merging code by using this guide https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by omman** [comment]
> Fixed on the latest 1.7.6, let us know if you have any issues - thank you!

https://github.com/inspireui/support/issues/3825#issuecomment-657515245
2 times showing See All Not Fixed Version 1.7.6 Just Today I update and checked...
