### ISSUE TITLE
Products and categories are not showing on Fluxstore Prestashop

### ISSUE THREAD

**Issue by gentianziu03** [inspireui/support#3898]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Products and categories are not showing on the app
+ Product & version: Fluxstore Prestashop - Flutter E-commerce Full App **Version: 1.0 **
+ Flutter (or React Native) version:  Flutter version 1.17.4
+ Testing Device/Simulator: sdk phone x86
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by vumanhsn97** [comment]
@gentianziu03 
Try to replace list file in this attach: 
[archive.zip](https://github.com/inspireui/support/files/4835106/archive.zip)

**Comment by gentianziu03** [comment]
i have another problem

![ezgif-1-408d6803237b](https://user-images.githubusercontent.com/46620232/85851110-61218280-b7ae-11ea-89df-f40b7a1a0552.gif)

on some of products shows **Failed assertion: boolean expression must not be null**

![ezgif-1-4e862b5e2265](https://user-images.githubusercontent.com/46620232/85851205-8d3d0380-b7ae-11ea-8c85-5e583ad21462.gif)
and on products with attributes when i want to add in cart or buy now it disappear

**Comment by vumanhsn97** [comment]
@gentianziu03 
check code in lib/models/product/product.dart like https://tppr.me/aJeDG

**Comment by gentianziu03** [comment]
> @gentianziu03
> check code in lib/models/product/product.dart like https://tppr.me/aJeDG
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/8c35c339ac1cf5869165baf65bb08d4016156d4c/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f66363130356636616663313832626532636531346163313163313533383134362e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Code_2020-06-26 18-22-12](https://tppr.me/aJeDG)**

the error: Failed assertion: boolean expression must not be null is fixed

but the error with attributes no?
how we can fix that?

**Comment by gentianziu03** [comment]
hello, i want to change currency to "Lekë" and lang to "AL"

also i have found an issue for the price

one the web i have a product with price  **413 Lekë**  including 20% tax   and i have discount this product with 30% final price will be **289** **leke**

the same product on the app shows the price **344 Lekë**  . I want to show the price one the app like it is on the web with discount

![Capture](https://user-images.githubusercontent.com/46620232/85917184-4572b680-b858-11ea-8ba5-d31a0fe15142.JPG)

**Comment by vumanhsn97** [comment]
@gentianziu03 
Out of stock can't add to cart
Language: Make sure you set language code is al in your website

**Comment by gentianziu03** [comment]
Of course i can't add of stock products, but in the web i have quantity above 10 pcs and on app i have out of stock.

Also why the price is diferent?

**Comment by gentianziu03** [comment]
another problem is that the app shows products that i have disabled from back office

**Comment by gentianziu03** [comment]
Hello, any support please?

**Comment by vumanhsn97** [comment]
@gentianziu03 
Can you send me your back office and account to vumanhsn97@gmail.com?

**Comment by gentianziu03** [comment]
yes, just sent

**Comment by gentianziu03** [comment]
Hello, i have replayed on email. Can i get any support please?

**Comment by vumanhsn97** [comment]
@gentianziu03 
Please update this module: 
[customapi.zip](https://github.com/inspireui/support/files/4902668/customapi.zip)

**Comment by gentianziu03** [comment]
yes, the products and categories are shows perect.

another issues are;

1) Problem with tax
2) Problem when i order products on the back office not shows the products

**Comment by vumanhsn97** [comment]
@gentianziu03 
Can you export your database in your site and send to vumanhsn97@gmail.com?
Thanks!

**Comment by gentianziu03** [comment]
yes

**Comment by gentianziu03** [comment]
hello, how i can fixed the problem with tax and products?

**Comment by gentianziu03** [comment]
hello, i have a week that i have send the database. Any answer?

**Comment by vumanhsn97** [comment]
@gentianziu03 
Please download lastest version and update this permission in Webservices https://tppr.me/fGCgb
Thanks!

**Comment by gentianziu03** [comment]
Hello, i have updated the app, the tax problem still exist and the products on the order are not show

**Comment by vumanhsn97** [comment]
@gentianziu03 
tax problem, can you explain more detail.
order product is working well in demo site. Can you share your admin account(this account can update module) and backoffice to vumanhsn97@gmail.com?

**Comment by gentianziu03** [comment]
I have 20% tax on every product and is not counted to real price
this is the price on the web and on the app the tax is not counted on the app like it is on the web.

![price](https://user-images.githubusercontent.com/46620232/88258959-a22f8880-ccc1-11ea-887e-1c320cc59b9e.JPG)

also another problem, all products that i have with combinations it shows out of stock like it is on the screen. 
I have sendet login details for back office, please check email

**Comment by gentianziu03** [comment]
HELLO, ANY CHANGES?

**Comment by vumanhsn97** [comment]
@gentianziu03 
Missing data when insert to order detail. Please check your table ps_order_detail and compare with default prestashop 1.7.x

**Comment by gentianziu03** [comment]
ps_order_detail is the latest update from prestashop so what to compare?

for the tax how i can fix the problem?
and for the products with combinations?

**Comment by vumanhsn97** [comment]
@gentianziu03 
Sorry for late response. Order detail issue fixed. Please check again.
Please waiting for next release to fix tax issue!
Thanks!

**Comment by gentianziu03** [comment]
Hello, yes it fixed but shows no product name on the product detail and invoice

![product](https://user-images.githubusercontent.com/46620232/88781710-030d0400-d18d-11ea-9d98-a1fe038628ef.JPG)
1) Not show the title of product
2) when the order is made i want to go in default status the order "Process in progress"
3) How i can add "ë" letter in language?

**Comment by vumanhsn97** [comment]
@gentianziu03 
2. You need to set current_state = 3 (id_order_state) in lib/services/prestashop.dart https://tppr.me/oShir
3. Please explain your issue

**Comment by gentianziu03** [comment]
3. the words that are with "ë" letter shows like it is on screenshot

![Capture](https://user-images.githubusercontent.com/46620232/88790350-559fed80-d198-11ea-96dd-67a959170139.JPG)

**Comment by vumanhsn97** [comment]
@gentianziu03 
Try to change with this code in lib/services/helper/prestashop_api.dart: https://tppr.me/2dg4y
return jsonDecode(utf8.decode(response.bodyBytes));

**Comment by gentianziu03** [comment]
ok this is fixed

another problem, i have a rule

on the order lower than 1000 leke is delivery 300 leke
on the order over than 1000 leke is delivery 200 leke
on the order over than 3000 leke is delivery 100 leke

on the prestashop web thic changes automatic by the amount of the cart

on the app it shows with 0$ value
![shipping](https://user-images.githubusercontent.com/46620232/88795781-dc58c880-d1a0-11ea-98ff-66b07c6dbfaf.JPG)

i dont want to shows the disabled delivery mthods

also for the payment

![payment](https://user-images.githubusercontent.com/46620232/88795976-38235180-d1a1-11ea-92da-1365678387e0.JPG)

I use only COD, but on app shows and other payment methods

How i can fix that?

**Comment by vumanhsn97** [comment]
@gentianziu03 
Shipping method fixed
Payment method follow this: https://github.com/inspireui/support/issues/4367#issuecomment-666081554

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by gentianziu03** [comment]
Hello, sorry for late response. The shipping method is fixed. Delivery cost it was from prestashop error and it is fixed. 
Now i am waiting for tax fix 
Products that are without title from backoffice on the order and invoice
And for the fix of products with combinations shows no stock
