### ISSUE TITLE
can't solve issue 3456

### ISSUE THREAD

**Issue by bigbossmaher** [inspireui/support#3936]
hello , 
i'm facing the same issue here 
https://github.com/inspireui/support/issues/3456
i'm using the 1.7.5 version 

i replaced the models/app.dart file , i tried flutter clean also 

the problem that the categories titles not loading under icons

config en
"items": [
        {
          "category": 172,
          "image": "assets/icons/categories/popular1.png",
          "colors": [
            "#827717",
            "#524c00"
          ],
          "originalColor": true
        },
        {
          "category": 22,
          "image": "assets/icons/categories/women1.png",
          "colors": [
            "#bf360c",
            "#870000"
          ],
          "originalColor": true
        },
        {
          "category": 24,
          "image": "assets/icons/categories/kids1.png",
          "colors": [
            "#00796b",
            "#48a999"
          ],
          "originalColor": true
        },
        {
          "category": 109,
          "image": "assets/icons/categories/home1.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },{
          "category": 20,
          "image": "assets/icons/categories/shoes1.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 177,
          "image": "assets/icons/categories/beauty1.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ],
          "originalColor": true
        },
        {
          "category": 21,
          "image": "assets/icons/categories/accessories1.png",
          "colors": [
            "#FB5252",
            "#3E6AB5"
          ],
          "originalColor": true
        },
        {
          "category": 175,
          "image": "assets/icons/categories/bags.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ],
          "originalColor": true
        },
        {
          "category": 19,
          "image": "assets/icons/categories/electronics.png",
          "colors": [
            "#5d4037",
            "#321911"
          ],
          "originalColor": true
        },
        {
          "category": 18,
          "image": "assets/icons/categories/man1.png",
          "colors": [
            "#c0ca33",
            "#8c9900"
          ],
          "originalColor": true
        },
        {
          "category": 26,
          "image": "assets/icons/categories/stationary1.png",
          "colors": [
            "#f06292",
            "#ba2d65"
          ],
          "originalColor": true
        },
        {
          "category": 25,
          "image": "assets/icons/categories/automative1.png",
          "colors": [
            "#12B58C",
            "#12B58C"
          ],
          "originalColor": true
        }
      ]

config ar 
"items": [
        {
          "category": 173,
          "image": "assets/icons/categories/popular1.png",
          "colors": [
            "#827717",
            "#524c00"
          ],
          "originalColor": true
        },
        {
          "category": 22,
          "image": "assets/icons/categories/women1.png",
          "colors": [
            "#bf360c",
            "#870000"
          ],
          "originalColor": true
        },
        {
          "category": 24,
          "image": "assets/icons/categories/kids1.png",
          "colors": [
            "#00796b",
            "#48a999"
          ],
          "originalColor": true
        },
        {
          "category": 109,
          "image": "assets/icons/categories/home1.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },{
          "category": 20,
          "image": "assets/icons/categories/shoes1.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 177,
          "image": "assets/icons/categories/beauty1.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ],
          "originalColor": true
        },
        {
          "category": 21,
          "image": "assets/icons/categories/accessories1.png",
          "colors": [
            "#FB5252",
            "#3E6AB5"
          ],
          "originalColor": true
        },
        {
          "category": 175,
          "image": "assets/icons/categories/bags.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ],
          "originalColor": true
        },
        {
          "category": 19,
          "image": "assets/icons/categories/electronics.png",
          "colors": [
            "#5d4037",
            "#321911"
          ],
          "originalColor": true
        },
        {
          "category": 18,
          "image": "assets/icons/categories/man1.png",
          "colors": [
            "#c0ca33",
            "#8c9900"
          ],
          "originalColor": true
        },
        {
          "category": 26,
          "image": "assets/icons/categories/stationary1.png",
          "colors": [
            "#f06292",
            "#ba2d65"
          ],
          "originalColor": true
        },
        {
          "category": 25,
          "image": "assets/icons/categories/automative1.png",
          "colors": [
            "#12B58C",
            "#12B58C"
          ],
          "originalColor": true
        }
      ]

the app aleady on playstore https://play.google.com/store/apps/details?id=com.shop.cheap

**Comment by ameenbadri7** [comment]
hello @bigbossmaher welcome back 

please use this as guide
```

 "layout": "category",
      "type": "icon",
      "wrap": false,
      "size": 1.0,
      "radius": 50.0,
      "items": [
        {
          "category": 140,
          "image": "assets/icons/categories/ic_tie.png",
          "colors": [
            "#3E6AB5",
            "#3E6AB5"
          ]
        },
.....
....
```

and also 

you can try to edit the file `lib\widgets\home\category\category_icon_items.dart`

inside ` line 124`
you can edit the text 
`   child: Text(
                        name,
                        style: TextStyle(
                          fontSize: kLayoutWeb ? 18 : 10.6,
                          fontWeight: FontWeight.w600,
                          color: Theme.of(context).accentColor,
                        ),
                        maxLines: 1,
                        textAlign: TextAlign.center,
                      ),`

and change the max lines: to 2 lines instead of 1.
and you can also change  ` textAlign`: from the center to
`TextAlign.left,`

please let me know if you have other problems I will help.

**Comment by bigbossmaher** [comment]
@ameenbadri7 
hello i think you have not understand me , it is a multilanguage app 
in arabic and english , on english version the category names are showed but on arabic no , it seems that config_en.json it is loading on both arabic and english , it should that config_ar loaded on arabic and config en for english 

please refer to this and read it 
https://github.com/inspireui/support/issues/3456

thanks

**Comment by bigbossmaher** [comment]
It means when i upload config_en to mstore api the categories are showed only in english and when i change the language to arabic the category name are not shown , and the inverse when i upload config_ar @minhcasi

**Comment by bigbossmaher** [comment]
any update please ? @minhcasi  @ameenbadri7 @vumanhsn97  ?

**Comment by ameenbadri7** [comment]
you should have two config_en + config_ar

the products lists should have different `category IDs` 

you can look to my config for my site Arabic and English files.
[config.zip](https://github.com/inspireui/support/files/4840921/config.zip)

please use [wpml ](https://wpml.org/documentation/related-projects/woocommerce-multilingual/)to translate new Arabic language strings for products and attributes and categories IDs.

use this also to know more about [multi-language](https://docs.inspireui.com/fluxstore/multi-language/) fluxstore projects.
 
thank you for your patients

**Comment by bigbossmaher** [comment]
hello ,
yes i'm using two configs , each one have specfic categories 
this is myconfig 

[config.zip](https://github.com/inspireui/support/files/4840932/config.zip)

the categories are already translated 

thanks

**Comment by ameenbadri7** [comment]
@bigbossmaher so your problem is solved?
please let us know if you still haveing any problems.

**Comment by bigbossmaher** [comment]
@ameenbadri7 
no sir the problem is not solved 
the categories labels are showed only the the uploded config
it means when i upload the config_ar the names are showed only on arabic languge
and when i upload the config_en the names are showed only on english languge

**Comment by bigbossmaher** [comment]
Is there any update ???I have another issue , 
hello , 
i'm using a single Verticale Layout in my app 1.7.5
`  "VerticalLayout":{
    "key":"84vy1djzd0",
    "category" : 215,
    "layout":"column",
    "name":"New Collection"},`
it is loading only with Iscaching False , when it is true , only the Heading is showed 

also is there any fast solution to make it cached , because the verticalLayout make the app loading too slow and buggy

**Comment by ameenbadri7** [comment]
we are trying our best to solve this issue 
I will not close this ticket until we solve this issue.
for now, you can use another layout to show recent like 

```
 {
      "name": "New Collcation",
      "layout": "staggered"
    }
```

to get recent products until we get the solution for this issue.

thank you for your patients.

**Comment by bigbossmaher** [comment]
thank you @ameenbadri7 

and what about the other issue ( multi-language )

**Comment by ameenbadri7** [comment]
could you please send us your common folder + config folder to our email. 

via minh@inspireui.com and declare your request based on my request so.

**Comment by bigbossmaher** [comment]
done .

**Comment by bigbossmaher** [comment]
hello , any updates ?

`by the way you last solution is not working is showing blank space {
      "name": "New Collcation",
      "layout": "staggered"
    }`

**Comment by ameenbadri7** [comment]
![Screenshot_20200630-024838_Skype_1](https://user-images.githubusercontent.com/37524186/86067018-6fa4be00-ba7c-11ea-9066-f5cd2b32ead6.jpg)

so you try our team temporary fix for the vertical double problem by changings you code as this picture. 

It will work with `vertical layouts` `Pinterest` option only  
Its not working with the other menu, default, etc.. 

![Screenshot_20200630-024808_Skype_1](https://user-images.githubusercontent.com/37524186/86067030-79c6bc80-ba7c-11ea-91c6-61b286c22f39.jpg)

**Comment by bigbossmaher** [comment]
a question please ? have you tested it on your machine before sending it to me ?

**Comment by ameenbadri7** [comment]
@bigbossmaher 
I have the latest `FLUXSTORE PRO` and also tried this code by my self! 
it's working with `pinterest` layout 

```
"VerticalLayout": {
    "layout": "pinterest",
    "name": "Recent Collections"
  },

```
add it before :

```
"Setting": {
    "MainColor": "#3FC1BE",
 ..........
```

**Comment by bigbossmaher** [comment]
@ameenbadri7 
For me is working only if isCashing is false , when is caching is true , only the heading of this verticallayout is showed,  no products.

**Comment by ameenbadri7** [comment]
```
The purpose of isCaching is to optimize the user's performance by not reloading config again when experiencing the app. That's why when you enable `isCaching`, product layout will not be loaded again. However, the product detail screen always needs to be reloaded due to special data events. Therefore, please consider using this feature if your site is mostly "static". Otherwise, turn this one off if you need your data is always up-to-date.
Best!
```
`This was a comment from one of our development lead team **@dttrung26** 
`
please don't use the caching on an e-commerce website and use it with other projects that are static, not dynamic. 

if you want to truly speed your site and app just optimize from the WordPress with plugins like regenerate Thumbnails and also using CDNA and get fast hosting server. 

please Let me know if you still have any questions.

**Comment by bigbossmaher** [comment]
from my personal experience when isCaching is enabled my app is running much faster 
you have not give me a logic answer about why horizontallayout is woking for isCaching true and not for verticalLayout ?
and it seems also that you forget the other issue about Multilanguage !

**Comment by ameenbadri7** [comment]
Thank you @bigbossmaher for your feedback. 
Dont worry
I will assign more advanced developers from our team to see your ticket.  

Thank you for your patience.

**Comment by minhcasi** [comment]
@bigbossmaher - 
Could i check if you have 

Could you help to share the admin login to the website via private email inspireui.team@gmail.com - we will help to check your admin setting - thank you!

**Comment by bigbossmaher** [comment]
@minhcasi 

it is sent , thanks , please help us ASAP

**Comment by bigbossmaher** [comment]
any updates please ?

**Comment by bigbossmaher** [comment]
After 5 days of waiting , the bugs still not fixed...

**Comment by minhcasi** [comment]
sent request to your email - pls move to one channel conversation that helps us support you better - thanks
