### ISSUE TITLE
Checkout Issue in FluxShopify

### ISSUE THREAD

**Issue by Artiiz-ZA** [inspireui/support#3951]
Fluxstore for Shopify 
Version 1.7.5

When trying to checkout with any products in the cart I get the error code in the Screenshot below. I see the same thing in your published version on the app store....

![image](https://user-images.githubusercontent.com/26002121/85928218-a37cb980-b8ab-11ea-993f-471c5979c620.png)

```
I/flutter (31364): [2020-06-27 17:19:11.010226Z][LiftNutrition][Cart] build
I/flutter (31364): Product { id: Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NDI0NDA3MzQ3NzU= name: Total Focus 4 }
I/flutter (31364): Product { id: Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE2NDg2NzY3OTg1MTk= name: Humans. Optimized. Nutrition Bundle }
I/flutter (31364): addItemsToCart productsInCart {Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NDI0NDA3MzQ3NzU=: 1, Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE2NDg2NzY3OTg1MTk=: 1}
I/flutter (31364): addItemsToCart productVariationInCart {Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NDI0NDA3MzQ3NzU=: null, Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE2NDg2NzY3OTg1MTk=: null}
I/flutter (31364): addItemsToCart null
I/flutter (31364): ::::addItemsToCart shopify error
I/flutter (31364): NoSuchMethodError: The getter 'id' was called on null.
I/flutter (31364): Receiver: null
I/flutter (31364): Tried calling: id
I/flutter (31364): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
I/flutter (31364): #1      ShopifyApi.addItemsToCart.<anonymous closure> 
package:liftnutrition/services/shopify.dart:745
I/flutter (31364): #2      Iterable.forEach  (dart:core/iterable.dart:279:30)
I/flutter (31364): #3      ShopifyApi.addItemsToCart 
package:liftnutrition/services/shopify.dart:739
I/flutter (31364): #4      ShopifyWidget.doCheckout 
package:liftnutrition/…/shopify/index.dart:96
I/flutter (31364): #5      _MyCartState.doCheckout 
package:liftnutrition/…/cart/my_cart.dart:316
I/flutter (31364): #6      _MyCartState.onCheckout 
package:liftnutrition/…/cart/my_cart.dart:307
I/flutter (31364): #7      _MyCartState.build.<anonymous closure>.<anonymous closure> 
package:liftnutrition/…/cart/my_cart.dart:227
I/flutter (31364): #8      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:779
I/flutter (31364): #9      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:862
I/flutter (31364): #10     GestureRecognizer.invokeCallback
```

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Artiiz-ZA** [comment]
![image](https://user-images.githubusercontent.com/26002121/85940273-bf1fa880-b91b-11ea-9f20-70a149bfd94c.png)

Requested files submitted

**Comment by Artiiz-ZA** [comment]
Good day,
Is there any feedback or further information required around this?
Thanks!

**Comment by luyx2412** [comment]
Hi @Artiiz-ZA Sorry about reply you late. Can you give me the payment.dart file?

Thanks

**Comment by Artiiz-ZA** [comment]
Please find in the below zip file

[payment.zip](https://github.com/inspireui/support/files/4849779/payment.zip)

Thanks

**Comment by luyx2412** [comment]
HI @Artiiz-ZA I just invited you to latest version which will resolve this issue. So please access and check about it.

Thanks

**Comment by Artiiz-ZA** [comment]
Thanks @luyx2412 
I will check it out and ensure that the issue is resolved and let you know here!

**Comment by Artiiz-ZA** [comment]
Hi @luyx2412 I was getting around to testing today and I see that the project on GitLab is gone?
How can I access the latest working version as you said I had access to?
thanks

**Comment by luyx2412** [comment]
Hi @Artiiz-ZA I just invited you to the repo again. 

Thanks

**Comment by Mrqozy** [comment]
Was this issue solved?
I reported a bug by email too. 

I want to buy your product but I first need to know if the bug is fixed! 

Thank you.

**Comment by Mrqozy** [comment]
> HI @Artiiz-ZA I just invited you to latest version which will resolve this issue. So please access and check about it.
> 
> Thanks

Hi. 
Was this issue solved? 
I want to buy Flux shopify app today.
But I need to know if the issue is fixed. 

Thank you.

**Comment by luyx2412** [comment]
Hi @Mrqozy The issue fixed in latest version. So feel free to buy FluxShopify, we will try support if appear the issues.

Thanks

**Comment by Mrqozy** [comment]
> Hi @Mrqozy The issue fixed in latest version. So feel free to buy FluxShopify, we will try support if appear the issues.
> 
> Thanks

Thank you. 
Can you update the android app?
I want to try the checkout before buying. 
Thanks.

**Comment by Artiiz-ZA** [comment]
Hi guys.

I have been testing the version off of GitLab and the same error persists and I am still unable to checkout..

**Comment by Artiiz-ZA** [comment]
Alright so I have come to an understanding of this error.
It occurs when the user clicks the quick add to cart button:
![image](https://user-images.githubusercontent.com/26002121/86559758-1269aa80-bf5d-11ea-9513-0d6eb2a734d2.png)

This adds the product to the cart but with no variation count. Resulting in a null ID on that field in the Shopify addItemsToCart section below:
`cartModel.productVariationInCart.keys.forEach((productId) {
          var variant = cartModel.productVariationInCart[productId];
          var productCart = cartModel.productsInCart[productId];

          print("addItemsToCart $variant");

          lineItems.add({"variantId": variant.id, "quantity": productCart});
        });`

Would the best way to fix this be to add a default variation for the products or change that method above?

**Comment by Mrqozy** [comment]
> Alright so I have come to an understanding of this error.
> It occurs when the user clicks the quick add to cart button:
> ![image](https://user-images.githubusercontent.com/26002121/86559758-1269aa80-bf5d-11ea-9513-0d6eb2a734d2.png)
> 
> This adds the product to the cart but with no variation count. Resulting in a null ID on that field in the Shopify addItemsToCart section below:
> 
> ```
> cartModel.productVariationInCart.keys.forEach((productId) {
>           var variant = cartModel.productVariationInCart[productId];
>           var productCart = cartModel.productsInCart[productId];
> 
>           print("addItemsToCart $variant");
> 
>           lineItems.add({"variantId": variant.id, "quantity": productCart});
>         });
> ```
> 
> Would the best way to fix this be to add a default variation for the products or change that method above?

It's very concerning the error still persists. 
I wanted to buy this app. 
But as it seems it still has some major bugs. 

Why did the developers closed the issue if the problem isn't solved? @luyx2412
