### ISSUE TITLE
[FluxStore 1.7.7 Woocommerce] Product-variants set to ANY value not passing through to checkout

### ISSUE THREAD

**Issue by and-eee** [inspireui/support#4003]
2 issue requiring your assistance:

### Issue 1

Having issue with the app when loading variable product page (60 variations) the loading animation never stops. Selecting variables while this is going on gives the following error log in console:

```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'price' was called on null.
Receiver: null
Tried calling: price

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      StateProductVariant.onSelectProductVariant.<anonymous closure> (package:fstore/screens/detail/product_variant.dart:135:23)
#2      WooVariantMixin.onSelectProductVariant (package:fstore/widgets/frameworks/woocommerce/woo_variant_mixin.dart:88:13)
#3      StateProductVariant.onSelectProductVariant (package:fstore/screens/detail/product_variant.dart:130:21)
#4      WooVariantMixin.getProductAttributeWidget.<anonymous closure> (package:fstore/widgets/frameworks/woocommerce/woo_variant_mixin.dart:115:57)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#726d1
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(300.6, 452.9)
  finalLocalPosition: Offset(23.6, 13.6)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════
```
<img width="380" alt="Screen Shot 2020-07-01 at 8 43 23 pm" src="https://user-images.githubusercontent.com/63891246/86236690-d7264f00-bbdd-11ea-8ba1-2fea2741796a.png">

Simple products and some variable products with fewer variables work fine. Caching is off.

### Issue 2

Push notifications not working on Android. Working fine on iOS version. Will load code for your reference shortly. Have been through your guides and double checked that all  have been followed but no luck.

Thank you.

**Comment by and-eee** [comment]
**Update:** Ignore issue 1, it was a product setup issue in Woocommerce. Catalogue visibility was set to 'Hidden'. Changed it to 'Shop Only' and it's working. 

Please help me with issue 2. Let me know if you need more information. Cheers.

**Comment by ameenbadri7** [comment]
hello, @and-eee Welcome back

please can you double-check this [ticket ](https://github.com/inspireui/support/issues/3151)
also the correct setup at this [guide ](https://docs.inspireui.com/fluxstore/firebase/) and let us know if you still have problems.

**Comment by and-eee** [comment]
Hi @ameenbadri7 , social logins are all working properly, most of what I'm seeing in that ticket relates to social loggins. I'm only experiencing issues with push notifications to Android via Firebase.

**Comment by ameenbadri7** [comment]
if you follow this [guide ](https://docs.inspireui.com/fluxstore/firebase/#android-integration)you will fix your problem.
please can you do it ?

**Comment by and-eee** [comment]
Hi @ameenbadri7 , I have gone through the whole thing again and it is still not working. I was also under the impression that social logins wouldn't work if Firebase wasn't set up correctly, and they're working fine. At the moment Firebase is able to send push notifications to iOS devices but not Android. I don't know if it makes a difference but I am still able to send push notifications to Android using OneSignal (I just want to be able to use either one or the other for both, and OneSignal isn't working on iOS at the moment).

Please tell me what you need from me to help troubleshoot this.

Thanks

**Comment by ameenbadri7** [comment]
@and-eee 
We want to thank you for your patience during this busy time.
please let us know if you still have this problem. its been 5 days? if everything working with you sir.
sending push notifications to Android using OneSignal is a hard task to do because the one signal plugin is not stable. we even disable it in our old fluxstore builds... 
if you still have problems I will our team look for it ASAP.
THANK YOU

**Comment by and-eee** [comment]
Hi @ameenbadri7 , yes I am still having this issue, I have been waiting for your response to tell me what files/information you need from me to check what aspect of the Firebase setup is causing the issue. Please advise.

**Comment by and-eee** [comment]
### Additional issue - some product variations not being passed to checkout

Please see example here, you will note that variants that do not effect pricing are not being included on the order at checkout, therefore not being included on the order in woocommerce. When placing an order via web these attributes are being included.

Product page:
![image](https://user-images.githubusercontent.com/63891246/86762267-e13ac880-c089-11ea-8424-4b3efd768d11.png)

Cart:
![image](https://user-images.githubusercontent.com/63891246/86762691-2959eb00-c08a-11ea-9dd7-8530369f0622.png)

Checkout (note **some variations are missing**)
![image](https://user-images.githubusercontent.com/63891246/86763008-61f9c480-c08a-11ea-863b-39a93ed2605d.png)

When placing the same order via website, all variants are being included:
![image](https://user-images.githubusercontent.com/63891246/86763312-966d8080-c08a-11ea-8e0d-3e54224ae0b7.png)

I have looked into this and found this link which might be useful in figuring this out. The attributes in question have all been set up as global attributes: [https://wordpress.org/support/topic/product-variation-doesnt-contain-attribute-woocommerce-rest-api/]

Thank you.

**Comment by minhcasi** [comment]
@and-eee - thank you for your input 

@minhtruong315 - pls help to investigate the missing data from mstore-api - thank you!

**Comment by and-eee** [comment]
Hi guys, the original ticket is now 12 days old now, just wanted to check in to see if we're making any inroads to finding a solution?

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. Although checking this Integration Issue is not included from our support scope - https://inspireui.com/support-policies/, but we’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by minhcasi** [comment]
@minhtruong315 - pls help with investigating

**Comment by and-eee** [comment]
### Additional Issue - 'per product' coupon codes

Please see below example. This coupon code has been set up to give a $1 discount on certain products (ie $1 off for each product purchased). When it is used in the app it has the correct effect on the final price but the notifications is confusing as it does not show the total discount amount, but rather the individual product discount.

![image](https://user-images.githubusercontent.com/63891246/87364615-77557e00-c5b7-11ea-9b3b-fa8595bdd97d.png)

**Comment by minhtruong315** [comment]
Hi @and-eee give me your skype? I will help you check remotely
Thanks

**Comment by and-eee** [comment]
hi @minhtruong315 , its andy@andeee.com

**Comment by and-eee** [comment]
Hi @minhtruong315 when will you be getting in touch? I will be available for the next 7-8 hours today. Currently waiting on solutions to 3 issues:

1. Product variants not being transferred to Woocommerce cart
2. Total coupon value not correctly displayed in cart notification
3. Android push notifications not working.

If you're prioritising jobs, I have listed these in order of urgency, so 1 is the most urgent for me and 3 the least urgent.

Thank you.

**Comment by minhcasi** [comment]
@and-eee - we will on help to check issue 1 & 2

the push notification issue could be fixed on this guide - https://medium.com/@inspireui/setup-firebase-cloud-messaging-fcm-push-notification-for-flutter-apps-8c767fe64e54 - thanks

**Comment by and-eee** [comment]
Hi guys, chasing this up as it has now been 4 days since your last message. I want to make sure you're not waiting for any information from me to provide a solution to the points 1 and 2 above. The app is now ready for publishing pending your solutiuons so your prompt attention would be greatly appreciated.

**Comment by minhtruong315** [comment]
Hi @and-eee can u give me your skype?
I will help you check via teamviewer.
Thanks

**Comment by and-eee** [comment]
Hi @minhtruong315 , I sent it 6 days ago (see above). It's andy@andeee.com

**Comment by minhtruong315** [comment]
I messaged you on the skype. pls check.
Thanks

**Comment by minhtruong315** [comment]
Hi @and-eee I messaged you on the skype. pls response.
Thanks

**Comment by rezassss** [comment]
haiiii..
i have same problem too, product variant not showing on product. my version was 1.7.5

**Comment by minhtruong315** [comment]
Hi @rezassss I'm working hard to try to fix product variant issue

**Comment by and-eee** [comment]
Hi guys, checking in to see if there's been any progress. Need to release this app or my funding is going to run out.

**Comment by and-eee** [comment]
@minhcasi @minhtruong315 hi guys, we're at the 6 week mark with this issue now, I am desperately in need of a solution, can I confirm you're prioritising resources to resolve this please?

**Comment by minhcasi** [comment]
@and-eee - please get the latest release that fix this issue `1.7.7` it is available on Gitlab and also from Codecayon today - thanks

**Comment by and-eee** [comment]
Thanks @minhcasi , just downloaded the code from Codecanyon and it's still on 1.7.6. Is there another place I can download 1.7.7. from?

**Comment by and-eee** [comment]
@minhcasi any news?

**Comment by minhtruong315** [comment]
Hi @and-eee We released Fluxstore 1.7.7. please try this version and remember to update MStore Api plugin as well

**Comment by and-eee** [comment]
Thank you @minhtruong315 , I have downloaded and started a fresh project as I had been carrying these changes over from 2 releases ago. I have updated flutter as I was not able to run `pub get` in **pubspec.yaml** and I am now getting this warning:

```
/Users/andy/Development/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in source...                          
Warning: You are using these overridden dependencies:

! flutter_svg 0.18.0
Running "flutter pub get" in source...                             63.0s
Process finished with exit code 0
```

What does this mean? Is it something at my end or is it code related?

**Comment by and-eee** [comment]
@minhcasi and @minhtruong315 , I've just gone through the setup process again (this is the 3rd time starting from scratch) from freshly downloaded code and the issue is **not fixed**, product attributes marked as variants set to use ANY value (ie the don't impact price) are still not being passed through to checkout. **Please advise urgently**.

**Comment by minhcasi** [comment]
@minhtruong315 - please help to investigate this issue as a high priority - thank you!

**Comment by and-eee** [comment]
@minhtruong315 thank you for your assistance, the code provided has resolved the issue with variants without specific values being passed through to woocommerce cart. Closing the ticket as discussed.

**Comment by Alnaggar94** [comment]
@and-eee @minhtruong315 - could you please share the solution?
