### ISSUE TITLE
app won't starting

### ISSUE THREAD

**Issue by smark98** [inspireui/support#4711]
Hi,

Last ticket: 4649

Still not working. I replaced app init, config files. Now not have spaschreen error but I got only white screen after 2 minutes just write lost conenction with the device.

So the app won't starting.

**Comment by simonpham** [comment]
Hi @smark98,
We apologize for any inconvenience. We didn't handle splash screen configuration well on this version.
You can try to replace `PNG` with `png` in `kSplashScreen` config
Example: 
replace `const kSplashScreen = "assets/images/splashscreen.PNG"`
with `const kSplashScreen = "assets/images/splashscreen.png"`

We will fix this issue in the upcoming version. Thank you for using our product.

**Comment by smark98** [comment]
Hi,

Actually i use png extension as small.

See the attached photo.

But now as I said I only got white screen and the app
Wont startimg.
![3AA688D7-4249-4169-9EB9-03FF61986675](https://user-images.githubusercontent.com/37720115/91020958-6b67cd80-e5f3-11ea-9525-b1221089b2b5.png)

**Comment by smark98** [comment]
Maybe the problem is the splashcreen type is flare and not png?

Const ksplashcreentype = “flare”;

**Comment by ameenbadri7** [comment]
You select your splash screen to be flare 
Const ksplashcreentype = “flare”;

but you are using a png file as the splach screen it have to be like that: 
const kSplashScreen = "assets/images/splashscreen.flr";
//const kSplashScreen = "assets/images/splashscreen.png";

also, if you have a custom `flare` make sure to edit the `lib/app_init.dart` file inline 146:
`startAnimation: 'fluxstore',`
to point toward your flare animation title.
have a look at our documentations to learn more:
https://docs.inspireui.com/fluxstore/common-issues/#other-common-issues

Thank you.

**Comment by smark98** [comment]
Hi yes I use splaschreen as png.

But the problem is still have. I got only white screen.

**Comment by simonpham** [comment]
@smark98 
You need to set `const kSplashScreenType = "static";` to use static image as splash screen.
Hope this will solve your issue. Good luck!

**Comment by smark98** [comment]
Hi,

Thank you.

I changed. Now I got new error and still white screen.

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The method '[]' was called on null.
Receiver: null
Tried calling: []("TabBar")

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      MainTabsState.loadTabBar (package:fstore/tabbar.dart:150:70)
#2      MainTabsState.afterFirstLayout (package:fstore/tabbar.dart:85:5)
#3      AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by simonpham** [comment]
Hi @smark98, could you share with us your `config_en.json` file?
Also, please tell us which version you are using.
Thank you.

**Comment by smark98** [comment]
I sent to support@inspireui.com.

**Comment by smark98** [comment]
An I use the latest version of fluxstore.

**Comment by simonpham** [comment]
> I sent to support@inspireui.com via weetransfer.

Hi @smark98, could you resend it to inspire.team@gmail.com? Thank you.

**Comment by smark98** [comment]
done

**Comment by smark98** [comment]
Also, please help me about IOS version because I try to build but always got error. flutter build ios same finish with build error. 
I haved same problem with 1.7.6 version but I tried same as last time but now didn't worked. ( delete cache, delete pod files, rebuild, upgrade flutter etc.)

**Comment by simonpham** [comment]
@smark98 have you opened the ios workspace (`Runner.xcworkspace`) in XCode and configured the development team and signing profile?

**Comment by smark98** [comment]
Yes, sure. That was the first thing what I do.

**Comment by smark98** [comment]
When I try to build directly from xcode I got these errors.

![Képernyőfotó 2020-08-26 - 16 44 52](https://user-images.githubusercontent.com/37720115/91318491-93099200-e7bb-11ea-9d65-fc537b8bdef6.png)

**Comment by simonpham** [comment]
> When I try to build directly from xcode I got these errors.
> 
> ![Képernyőfotó 2020-08-26 - 16 44 52](https://user-images.githubusercontent.com/37720115/91318491-93099200-e7bb-11ea-9d65-fc537b8bdef6.png)

Please make sure you opened `Runner.xcworkspace`, not `Runner.xcproject`.

**Comment by smark98** [comment]
Im sure about that. since I have made this mistake last time.

**Comment by simonpham** [comment]
> Hi,
> 
> Thank you.
> 
> I changed. Now I got new error and still white screen.
> 
> ════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
> The following NoSuchMethodError was thrown during a scheduler callback:
> The method '[]' was called on null.
> Receiver: null
> Tried calling:
> 
> When the exception was thrown, this was the stack:
> #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> #1 MainTabsState.loadTabBar (package:fstore/tabbar.dart:150:70)
> #2 MainTabsState.afterFirstLayout (package:fstore/tabbar.dart:85:5)
> #3 AfterLayoutMixin.initState. (package:after_layout/after_layout.dart:10:38)
> #4 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)

Hi @smark98,

For this error, we have checked your `config_es.json` and `config_en.json` and found a problem in the syntax.
I have fixed it for you:
• config_en: https://gist.github.com/simonpham/f41e3476aecda591e3309415ff5320fc
• config_es: https://gist.github.com/simonpham/3a11da2a4284858033857050b93c6269

**Comment by smark98** [comment]
Hi,

Thank you very much now I see the problem. I do this modification with all config file.

Now working fine but only the android version.

The IOS version still have issue when i try to build.(which i writed in my last messages.)

**Comment by smark98** [comment]
But Now the app runnig when I click the category menu I got this error.
The app not crashing or something else just i see this error: 

nother exception was thrown: Rect argument contained a NaN value.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
Rect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 28: '<optimized out>'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Container file:///Users/sebokmark/Desktop/bagoly_fogado/app/source/lib/widgets/home/logo.dart:36:16
When the exception was thrown, this was the stack: 
#2      _rectIsValid (dart:ui/painting.dart:28:10)
#3      Canvas.drawRect (dart:ui/painting.dart:3729:12)
#4      _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7250:22)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
...
The following RenderObject was being processed when the exception was fired: _RenderColoredBox#e8029 relayoutBoundary=up6
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, 0.0<=h<=45.0)
...  size: Size(411.4, 45.0)
...  behavior: opaque
RenderObject: _RenderColoredBox#e8029 relayoutBoundary=up6
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, 0.0<=h<=45.0)
  size: Size(411.4, 45.0)
  behavior: opaque
...  child: RenderFittedBox#3b735 relayoutBoundary=up7
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=45.0)
...    size: Size(411.4, 45.0)
...    fit: cover
...    alignment: center
...    textDirection: ltr
...    child: RenderConstrainedBox#89260 relayoutBoundary=up8
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(341.7, 50.0)
...      additionalConstraints: BoxConstraints(w=341.7, 50.0<=h<=Infinity)
...      child: RenderStack#14b2b relayoutBoundary=up9
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=341.7, 50.0<=h<=Infinity)
...        size: Size(341.7, 50.0)
...        alignment: AlignmentDirectional.topStart
...        textDirection: ltr
...        fit: loose
...        child 1: RenderConstrainedBox#800c0 relayoutBoundary=up10
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=341.7, 0.0<=h<=Infinity)
...          size: Size(341.7, 50.0)
...          additionalConstraints: BoxConstraints(0.0<=w<=Infinity, 50.0<=h<=Infinity)
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by simonpham** [comment]
> When I try to build directly from xcode I got these errors.
> 
> ![Képernyőfotó 2020-08-26 - 16 44 52](https://user-images.githubusercontent.com/37720115/91318491-93099200-e7bb-11ea-9d65-fc537b8bdef6.png)

Hi @smark98,

I think you removed Podfile which includes OneSignal dependency.

![image](https://user-images.githubusercontent.com/8846657/91785559-da66a700-ec2f-11ea-83d4-0bdfae0c266b.png)


If you use Firebase Cloud Messaging for Push notification, you can remove the code of OneSignal in AppDelegate.swift, so it  will look like below (the whole file will be like this):

```swift
import UIKit
import Flutter
import GoogleMaps
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GMSServices.provideAPIKey("your-google-api-key-here")
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

**Comment by smark98** [comment]
Hi, 

Thank you now I can build to the IOS simulator. But when I try to archice or do flutter build ios command i get error.

![Képernyőfotó 2020-09-01 - 18 55 41](https://user-images.githubusercontent.com/37720115/91883534-dca72080-ec84-11ea-88a3-14e22743233e.png)

**Comment by smark98** [comment]
Now I deleted on signal extension from main folder and then sucessfully archived.

I would like to ask is it problem or how can i change this to my own domain?

com.apple.developer.associated-domains
applinks:inspireui.com

**Comment by simonpham** [comment]
> Now I deleted on signal extension from main folder and then sucessfully archived.
> 
> I would like to ask is it problem or how can i change this to my own domain?
> 
> com.apple.developer.associated-domains
> applinks:inspireui.com

You can check Apple's documentation for iOS deep link configuration:
https://developer.apple.com/documentation/safariservices/supporting_associated_domains

**Comment by smark98** [comment]
Okay thank you i will try it.

BTW when i try to log in with sms the app crash.🤷‍♂️ 
I do not know what is the problem.

**Comment by simonpham** [comment]
@smark98,
Please go to your firebase project, enable SMS login then download the latest google-services .json & .plist file.
Additional step for iOS, please follow this answer from StackOverflow: https://stackoverflow.com/a/52303358/9015744

**Comment by smark98** [comment]
> > Now I deleted on signal extension from main folder and then sucessfully archived.
> > I would like to ask is it problem or how can i change this to my own domain?
> > com.apple.developer.associated-domains
> > applinks:inspireui.com
> 
> You can check Apple's documentation for iOS deep link configuration:
> https://developer.apple.com/documentation/safariservices/supporting_associated_domains
> 
> > **[Apple Developer Documentation](https://developer.apple.com/documentation/safariservices/supporting_associated_domains)**

Where can I find this file in you app which is write in this documentation?

**Comment by minhcasi** [comment]
@smark98 - try to double-check your bundle ID setting - https://docs.inspireui.com/fluxstore/delivery-android/#12-change-the-app-bundle-id-package-name - it should match with your Firebase config

**Comment by minhcasi** [comment]
Let us know your checking, thank you!

**Comment by smark98** [comment]
I will tell you today.

**Comment by smark98** [comment]
I tried this documentation but but still have issue:


flutter: [2020-09-08 16:59:09.969835Z][Fluxstore]screenName /login
flutter: [2020-09-08 16:59:12.592366Z][Fluxstore]screenName null
Lost connection to device.

**Comment by smark98** [comment]
Also i see this version not have internet connection animation. I founded the flr file. But id i open the app without internet connection it is not showing. Need to activate somewhere or how?

**Comment by simonpham** [comment]
> Also i see this version not have internet connection animation. I founded the flr file. But id i open the app without internet connection it is not showing. Need to activate somewhere or how?

When you have no Internet connection, open any product list page (tap on any category) it will show the animation.

**Comment by simonpham** [comment]
> I tried this documentation but but still have issue. The app also crash with sms and google login. The apple login works perfectly. But some issue I have with android because the notifcation also not recive only just for IOS.
> 
> flutter: [2020-09-08 16:59:09.969835Z][Fluxstore]screenName /login
> flutter: [2020-09-08 16:59:12.592366Z][Fluxstore]screenName null
> Lost connection to device.

Please find the full error log with `adb logcat`.
I'm pretty sure your SHA1 hash is not correctly configured.
Please add the correct SHA1 hash generated from your keystore and add it to Firebase project. Then download the latest google services json to your `android/app` folder.
Then generate a signed APK and test it.
If you want to test on debug mode, please add debug SHA1 hash to Firebase project as well.

**Comment by smark98** [comment]
> > Also i see this version not have internet connection animation. I founded the flr file. But id i open the app without internet connection it is not showing. Need to activate somewhere or how?
> 
> When you have no Internet connection, open any product list page (tap on any category) it will show the animation.

I try this but nothing.

**Comment by smark98** [comment]
> > I tried this documentation but but still have issue. The app also crash with sms and google login. The apple login works perfectly. But some issue I have with android because the notifcation also not recive only just for IOS.
> > flutter: [2020-09-08 16:59:09.969835Z][Fluxstore]screenName /login
> > flutter: [2020-09-08 16:59:12.592366Z][Fluxstore]screenName null
> > Lost connection to device.
> 
> Please find the full error log with `adb logcat`.
> I'm pretty sure your SHA1 hash is not correctly configured.
> Please add the correct SHA1 hash generated from your keystore and add it to Firebase project. Then download the latest google services json to your `android/app` folder.
> Then generate a signed APK and test it.
> If you want to test on debug mode, please add debug SHA1 hash to Firebase project as well.

When I need to use the SHA1 key from google play console? 
Same problem have in IOS version if I use wrong SHA1 or just in the android. 
Also If the android SHA1 wrong why wrong the sms login in IOS?

**Comment by simonpham** [comment]
Hi @smark98,

I am sorry for the late reply.
To get the SHA1 key from keystore, you can follow this official document: https://developers.google.com/android/guides/client-auth

For iOS, please open `project folder/ios/GoogleService-Info.plist` then copy this from `REVERSED_CLIENT_ID`

![image](https://user-images.githubusercontent.com/8846657/93015324-c08b7380-f5e2-11ea-8853-25b423d0f39b.png)

Then paste to this `CFBundleURLSchemes` in `project folder/ios/Runner/Info.plist`:

![image](https://user-images.githubusercontent.com/8846657/93015335-d305ad00-f5e2-11ea-8f31-e659219a44c9.png)

Please tell me if you have any problems. Thank you.
