### ISSUE TITLE
Cant Authenticate code when login with SMS

### ISSUE THREAD

**Issue by silamutungi** [inspireui/support#4897]
**_Step 1 (require): describe detail issues & screenshots_**
I've set up a login with SMS. After I enter the number the next screen won't let me enter the code to authenticate (or auto authenticate) it just shows the error below.

+ Product & version:
Fluxstore listing 1.4.3
+ Flutter (or React Native) version: 
Flutter 1.20.3
+ Testing Device/Simulator: 
Both iOs and Android

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **
See ticket #4831

![error](https://user-images.githubusercontent.com/7536714/92317081-56a31680-efb1-11ea-824f-aa21ecac211c.png)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Sorry i could not see the error on your screenshot, could i know if you got the SMS message?

**Comment by silamutungi** [comment]
I got the sms message. But when I tried to enter the code this is what I
see. I can’t enter anything.

**Comment by silamutungi** [comment]
Here's the screenshot again
![error](https://user-images.githubusercontent.com/7536714/92341008-39ce1800-f071-11ea-8658-1bb9e90da057.jpg)

**Comment by minhcasi** [comment]
Thank you - I got your point, let me raise this issue to the team and get back you shortly - thank you!

**Comment by silamutungi** [comment]
I added the addListingURl to config.dart but still not working.
![IMG_C8386A96C8E1-1](https://user-images.githubusercontent.com/7536714/92509491-2df06c00-f1bf-11ea-8052-17aebbf409f6.jpeg)

**Comment by minhcasi** [comment]
note with investigating - thank you!

**Comment by silamutungi** [comment]
Thank you!

**Comment by silamutungi** [comment]
@minhcasi Category names are not showing below some icons. The only one showing is Bars.
![IMG_29B5CE8CE4C5-1](https://user-images.githubusercontent.com/7536714/92966516-8b3d2500-f42c-11ea-9750-851024c7645b.jpeg)

**Comment by minhcasi** [comment]
@silamutungi - could i check if the category is matching with your ID from Wordpress site?

**Comment by silamutungi** [comment]
It does because when I click on them they take me to the category page

**Comment by philipvu30** [comment]
Hi,

- For sms verification issue, in the file lib/screens/login_sms/verify.dart, add this line
![image](https://user-images.githubusercontent.com/54442328/93181577-d0ca5c80-f762-11ea-935f-9250556f7d1e.png)

**Comment by philipvu30** [comment]
> I added the addListingURl to config.dart but still not working.
> ![IMG_C8386A96C8E1-1](https://user-images.githubusercontent.com/7536714/92509491-2df06c00-f1bf-11ea-8052-17aebbf409f6.jpeg)

Hi, 

May I ask what is your current version of ListApp Mobile Manager plugin?
If you haven't updated it in awhile. Please do so.

Thanks.

**Comment by philipvu30** [comment]
> @minhcasi Category names are not showing below some icons. The only one showing is Bars.
> ![IMG_29B5CE8CE4C5-1](https://user-images.githubusercontent.com/7536714/92966516-8b3d2500-f42c-11ea-9750-851024c7645b.jpeg)

This issue usually happens due to empty categories. Please check that if those categories have any items.
If they do, please send me your config.json and config.dart to this email: toan@inspireui.com.

Thanks.

**Comment by silamutungi** [comment]
List app mobile manager Version 1.6.5

**Comment by philipvu30** [comment]
Hi,

I'm so sorry that we've published new feature without checking. Currently, the version 1.6.5 doesn't have the endpoint "add-listing" yet. 
If you don't mind, you can replace this file [class.api.fields.php.zip](https://github.com/inspireui/support/files/5230272/class.api.fields.php.zip) in the Listapp Mobile Manager. It can be found in the folder ListApp Mobile Manager -> rest-api -> class.api.fields.php.
Or wait for our update on the plugin. It will be published within today.

Thank you.

**Comment by silamutungi** [comment]
I replaced the file and still getting the same error message.
Thanks

-Sila

**Comment by philipvu30** [comment]
@silamutungi  what error?

**Comment by silamutungi** [comment]
@philipvu30 
![C72F9BBE-1C00-44EE-9895-3C0957C45194](https://user-images.githubusercontent.com/7536714/93413123-65ac8300-f853-11ea-9d6c-213997e5c0ff.jpeg)

**Comment by philipvu30** [comment]
Hi,

1. I don't know if you correctly modified the file I gave. But here is the instruction:
- Head to this file and replace its content with this [class.api.fields.php.zip](https://github.com/inspireui/support/files/5235913/class.api.fields.php.zip)

![image](https://user-images.githubusercontent.com/54442328/93413416-6f70cd80-f8c9-11ea-9512-e01087345a14.png)

2. The "onTap solution" only allowed you to able to type. For this error you got on the SMS verification, it relates to Firebase API. Please check that if:
- The API's quota in the Firebase Console is exceeding the request quota.
- The API is enabled in the Developer Console for the application you are testing.
- The SHA key has been inserted properly.

**Comment by philipvu30** [comment]
Hi,

I just noticed that your site has over 100 categories. Currently, this app only supports a maximum of 100 categories at a time. That's the reason why your category's names don't show up on HomePage.
We'll improve that feature later. For now, please only use the category's IDs on your first page.

Thank you.

**Comment by silamutungi** [comment]
The add listing fix worked. Thank you!

I'm looking into the SMS verification process.

**Comment by silamutungi** [comment]
This is a big issue because most directories and listings have more than a
hundred categories. Yelp has 1200 categories (
https://blog.yelp.com/2018/01/yelp_category_list#section3)

Does this mean that when people use to search only the 100 categories will
show?

Please advice.

-SIla

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com - please help to move your next comment on the new support system - thank you for your time!
