### ISSUE TITLE
Please solve the below issues.

### ISSUE THREAD

**Issue by minndfreakanime** [inspireui/support#4913]
Issues regarding design and payment

1 - Design issue

 The full name of category is not displayed in the top. For example category name is personal care, but only personal is displayed. Same for Dairy and bakery, only Dairy is displayed.
Please provide the solution in this case. Screenshot attached.
![WhatsApp Image 2020-09-04 at 12 12 07 PM](https://user-images.githubusercontent.com/20972844/92374532-7bb49800-f11d-11ea-9f43-5aa3e09e8510.jpeg)

2 - Checkout Issue

While checkout we get stuck on the shipping tab.Cannot move forward to preview tab. Screenshot attached.
  Please provide the solution in this case.  
![WhatsApp Image 2020-08-30 at 11 21 28 PM](https://user-images.githubusercontent.com/20972844/92374603-97b83980-f11d-11ea-86da-769f7f8f3f36.jpeg)

3-  Payment issue
 We have integrated razorpay payment gateway. As we were facing issue with shipping tab, we modified the code to enable shipping false and proceed to checkout to test the payment. Inspite of putting the correct key we get an error as API key is invalid. We have attached the screenshot. Parameters used in code are keyId:, paymentMethodId:,enabled. Please let us know if any other parameter is to be used.
![WhatsApp Image 2020-09-04 at 12 12 17 PM](https://user-images.githubusercontent.com/20972844/92374628-a141a180-f11d-11ea-8dd8-4bc94c771f84.jpeg)

Note: - We are not integrating payment on our website. We have just enabled, did not enter any details.

Note - If we enable shipping false, we do not get shipping address of customer. So shipping address must be true.

**Comment by minndfreakanime** [comment]
@minhcasi @minhtruong315 Can you please look into it fast as we have to deploy it fast. Been a month and we want to start it.

**Comment by minhtruong315** [comment]
@minndfreakanime pls upload your source code to github and invite me: minhtruong315@gmail.com
And send me admin account to login your website as well
Thanks

**Comment by minndfreakanime** [comment]
We have shared you the access to our github repo on your email id as well as website details.

**Comment by minndfreakanime** [comment]
> @minndfreakanime pls upload your source code to github and invite me: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)
> And send me admin account to login your website as well
> Thanks

I have done it long time ago. Please follow up on the issue

**Comment by minndfreakanime** [comment]
@minhcasi please look into this it's been a long time no one looking into it

**Comment by minhtruong315** [comment]
@minhtruong315 can u give me the link? I dont see it in my email. Thanks

**Comment by minndfreakanime** [comment]
@minhtruong315 
Below is link for the website login
https://sanilrodrigues.com/wp-admin

Below is this link to repo. It's private but have given u access.
https://github.com/minndfreakanime/DoorDrop

Need anything else we have email you the details for login from email id thomsondsouza33@gmail.com

Also access have been given to you for the repository.
If you can't find it please let us know will share the access again to same email.

**Comment by minndfreakanime** [comment]
Do you need anything else

**Comment by minhtruong315** [comment]
@minndfreakanime I will check and let you know the result

**Comment by minhtruong315** [comment]
@minndfreakanime pls pull the source code and check again. I fixed issue 1, 2. For Razorpay checkout, you need to be sure that your website must work well. Can u checkout with razorpay on your website?

**Comment by minndfreakanime** [comment]
@minhtruong315 Bro we have not added razor pay in our website. Cz we are nit going to make website live it just going to be to hold woocomerce data.
So do we need to add razor pay in website also so it to be working on app

**Comment by minndfreakanime** [comment]
1st error is not yet fixed. Also there is one more error in app. Icons in below doesn't load.
Screenshot below.
![Screenshot_20200913-233538__01](https://user-images.githubusercontent.com/20972844/93025292-5a224780-f61a-11ea-8ada-36aa26bca571.jpg)

**Comment by minhtruong315** [comment]
@minndfreakanime Razorpay payment is using NativeOnePageCheckout. it use checkout page in your website to checkout. so you need to add razorpay in your website.

**Comment by minndfreakanime** [comment]
Ok sure. Can you please look into the remaining issues that I just send the screenshot

**Comment by minhtruong315** [comment]
<img width="1066" alt="Screen Shot 2020-09-15 at 8 40 32 AM" src="https://user-images.githubusercontent.com/10402500/93154960-2edd4c80-f72f-11ea-8604-c0987239f5be.png">
You didn't add icons to assets

**Comment by minhtruong315** [comment]
@minndfreakanime pls pull the source code to check category name
<img width="477" alt="Screen Shot 2020-09-15 at 8 50 28 AM" src="https://user-images.githubusercontent.com/10402500/93155544-8fb95480-f730-11ea-96e5-cff45aa3d584.png">
