### ISSUE TITLE
[ cestore ] Problem Deploying website on Ubuntu 16.04 digitalocean

### ISSUE THREAD

**Issue by s3665959** [inspireui/support#589]
Product: [cestore]
Item Purchase Code:
43fdac4f-37a3-4414-9687-c850d0******

i am trying to deploy the cestore website on Ubuntu 16.04 digitalocean. 
i've follow the step on your document ( https://docs.inspireui.com/cestore-web/deploy/ )

at the step 5. Preparing Database (https://docs.inspireui.com/cestore-web/deploy/#5-preparing-database)

Run npm run setup on Cezerin container to add default data and create indexes.
`sudo docker exec store bash -c "npm run setup"`

but i dont the folder  Cezerin on the web root directory 
![image](https://user-images.githubusercontent.com/42608262/57833081-6e1a2700-77e3-11e9-8a76-8074b5d13aae.png)

where to run the `sudo docker exec store bash -c "npm run setup"`

next question is , if i done all the step in your doc (https://docs.inspireui.com/cestore-web/deploy/ )

then 
i need to upload the web folder from my local computer to the host right? and upload it to which directory?

upload this whole folder to where?
![image](https://user-images.githubusercontent.com/42608262/57833356-0adcc480-77e4-11e9-8aeb-14379886790e.png)

thank you
naka

**Comment by s3665959** [comment]
Please help @minhcasi

**Comment by minhcasi** [comment]
Hi, we will update the document and let you know!

Or, could you able to share the account access private to my team: @minhtruong315 - we will help for the config 
Also, zip your delivery package and send us (you can change the log in detail after the setup)

- thank you!

**Comment by minhtruong315** [comment]
done

**Comment by s3665959** [comment]
1. it's not done yet!!. i still cannot access my website via my domain. only can access from IP.

@minhtruong315  ask me to contact you (@minhcasi ) for your permission to fix my problem.
please tell him to complete the job.

ps. if you have a complete document , it would be better.  because  right now your document is incomplete and unclear, as i am a user i cannot set it up without your help. 

thank you.

**Comment by minhcasi** [comment]
We will update the video guide document with the detail config and get back you shortly - thanks

**Comment by s3665959** [comment]
any update? @minhcasi

**Comment by s3665959** [comment]
i would like to get a refund on cestore ,
I cannot get this cestore to work . your supporter is not helping me .
I have make request refund on evanto.. Please approve it   
thank you @minhcasi
