### ISSUE TITLE
[Mstore Pro] 3.9.3 -  IOS error when changing the language 

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#885]
Fresh installation of MStore  3.9.3

in IOS ...when I change the language in the App ... I got the error as attachment below ..

<img width="380" alt="Screen Shot 1440-12-03 at 11 08 22 PM" src="https://user-images.githubusercontent.com/23431061/62528807-20dbad80-b846-11e9-9224-2012a75e1e46.png">

when I run this command 
cd ios/ && rm -rf build/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd ../

I got the following worning  

<img width="758" alt="Screen Shot 1440-12-05 at 11 40 52 PM" src="https://user-images.githubusercontent.com/23431061/62575564-aa6d9880-b8a3-11e9-9cfd-bdebd4083ef3.png">

How to solve this issue ?

**Comment by minhcasi** [comment]
Hi, could you remove the node_module and zip the package, then sent to our email support@inspireui.com via https://wetransfer.com - we will help for checking this issue - thanks

**Comment by yosefasad** [comment]
I already sent  node_module in  zip package to your email support@inspireui.com via https://wetransfer.com ... 

Thank you in advance ...

**Comment by yosefasad** [comment]
any update?

**Comment by minhcasi** [comment]
Fixed 3.9.4 - we will update this release on early next week - thank you!

**Comment by yosefasad** [comment]
Thank you for your support

**Comment by yosefasad** [comment]
Download today  Mstore 3.9.4 

the issue still exist ...not solved yet .......

I removed node_module and  send zip package of 3.9.4 to your email support@inspireui.com via https://wetransfer.com from my email under the name of 
"[Mstore Pro] 3.9.3 - IOS error when changing the language #885"

**Comment by minhcasi** [comment]
Hi, could you help to download again the mstore-3.9.4b.zip version as it is fixed this build issue

You can also fix by add new config to Podfile
```
pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'
```

And replace in package.json
```
 "react-native-restart": "https://github.com/avishayil/react-native-restart.git",
```

**Comment by yosefasad** [comment]
it works now ...thank you very much

**Comment by minhcasi** [comment]
you're welcome, thank you!
